### ISSUE TITLE
Unable to import ipcRenderer in Preload layer after removal of "unplugin-auto-expose"

### ISSUE THREAD

**Issue by iaaanz** [cawa-93/vite-electron-builder#1021]
**Describe the bug**
It's not possible to import ipcRenderer in the preload layer, although this was previously possible.

**To Reproduce**

1. Create any TypeScript file within preload/src and import ipcRenderer.
2. Export it in the index.ts file in preload.
3. Run the project.

**Expected behavior**
ipcRenderer should be detected and function as it did previously.

**Screenshots**
![image](https://github.com/user-attachments/assets/f8db7def-cc36-4cd9-9c1a-a66a09ad0549)

**Additional context**
This bug affects the functionality of the preload layer, and the code was working correctly before the removal of unplugin-auto-expose.

**Comment by cawa-93** [comment]
Will it work if you use named export instead of `default` ?

**Comment by iaaanz** [comment]
Actually the problem is when importing electron package, and not when i am exporting my ipcRenderer.

![image](https://github.com/user-attachments/assets/00b96e85-bd84-4981-bcc5-f166098affc6)
![image](https://github.com/user-attachments/assets/fd5c601d-dd8b-4626-b16d-2241e34a9f9a)

**Comment by iaaanz** [comment]
Do you have an workaround in mind that is easy to implement?

**Comment by iaaanz** [comment]
Thanks, worked 😁
