### ISSUE TITLE
Relative Paths in preload layer cause renderer crash

### ISSUE THREAD

**Issue by iaaanz** [cawa-93/vite-electron-builder#1024]
**Describe the bug**
Using relative paths in the preload layer causes the renderer to crash at runtime.

**To Reproduce**

1. Import a module in the preload layer using a relative path, e.g., "src/module/test.ts".
2. Export this module in index.ts of preload and import it in the renderer.
3. Run the project.

**Expected behavior**
The path should be resolved at runtime without issues, as no errors are shown during type checking, but the renderer crashes at runtime.

**Screenshots**
![image](https://github.com/user-attachments/assets/1da63433-63bd-4320-a256-077f642a8f31)
![image](https://github.com/user-attachments/assets/058fa080-dee7-42c6-bd74-ae823acd99ed)

**Additional context**
I tried every possible configuration in tsconfig, but without success. I’m out of ideas on how to resolve this.

**Comment by cawa-93** [comment]
May you provide an reproduction?
