### ISSUE TITLE
Possible bug: Built preload script lost on watch reload

### ISSUE THREAD

**Issue by danebulat** [cawa-93/vite-electron-builder#1028]
Firstly, thank you for creating a fantastic template. I'm learning a lot from studying your code and project setup.

### Describe the bug
The built `dist/preload.js` script is lost when `watch.js` is running and a source file is updated. This happens when the `build.emptyOutDir` property is set to `true` in any of the Vite configs.  When `build.emptyOutputDir` is set to `false`, application reload works as expected when making changes to files during development.

The `vite-electron-builder` template sets `build.emptyOutputDir` to `true` on each Vite config object.

### To Reproduce
I have created a small demo application to demonstrate this behaviour.

1. Clone my demo app at https://github.com/danebulat/electron-react-template/tree/db-demo-vite-watch:
```
git clone -b db-demo-vite-watch https://github.com/danebulat/electron-react-template
cd electron-react-template
```
3. Install dependencies: `yarn install`.
4. Generate vendors: `yarn run vendors` (runs `scripts/update-electron-vendors.js`)
6. Set the `build.emptyOutDir` property to `true` in the Vite configs at:
  - `config/vite.main.config.js`  
  - `config/vite.preload.config.js`
  - `config/vite.renderer.config.js`
7. Run the watch script:  `yarn run watch`
8. Make a small change (such as inserting a newline) in `src/main.ts` and save the file.
9. Notice that the `dist/preload.cjs` file has not been re-built.

### Expected behavior
The `dist/preload.cjs` file should be re-built and present after making changes to a file with the `watch.js` script running.

### Additional context
- The demo app uses the `watch.js` and `update-electron-vendors.js` scripts, along with the Vite configs from the `vite-electron-builder` template.
- The renderer is sandboxed which requires the preload script to be compiled in `cjs` format.
- Yarn used as the package manager instead of npm.
- I wish to replace Electron Forge with an Electron Builder setup. This is why an Electron Forge config also exists in the demo app, but is unrelated to this particular issue.

**Comment by cawa-93** [comment]
I think it's because all your configs targeting to build in same place

`main` -> `./dist/<add main files>`
`preload` -> `./dist/<add preload files>`

main changed -> remove `./dist` -> `./dist/<add main files>`

**Comment by danebulat** [comment]
@cawa-93 You are right!

I set `build.emptyOutDir` to `true` only for the renderer config, with the other configs having it set to `false`. That fixed the issue.

Thank you very much for figuring it out.
