### ISSUE TITLE
There are no scripts for steps 4 and 7 of contributing.md's "Repo Setup".

### ISSUE THREAD

**Issue by wisdomstar94** [cawa-93/vite-electron-builder#1032]
**Describe the bug**
The title is the same.

I wanted to contribute to a certain part, so I forked and cloned the repository.

After I finished working on the part I wanted to contribute, I tried to proceed with the ["Repo Setup"](https://github.com/cawa-93/vite-electron-builder/blob/main/contributing.md#repo-setup) step shown in ["contributing.md"](https://github.com/cawa-93/vite-electron-builder/blob/main/contributing.md#repo-setup), but there were no scripts for 4 or 7 in the package.json in the actual clone storage.

**To Reproduce**
1. git clone `https://github.com/cawa-93/vite-electron-builder.git`.
2. open `package.json` file.
3. It is shown that there is no lint and format script.

**Expected behavior**
As stated in ["Repo Setup"](https://github.com/cawa-93/vite-electron-builder/blob/main/contributing.md#repo-setup) on ["contributing.md"](https://github.com/cawa-93/vite-electron-builder/blob/main/contributing.md#repo-setup), the script must exist.

**Screenshots**
![image](https://github.com/user-attachments/assets/a90017f3-7008-4263-bcd8-84cc05531b01)

**Additional context**

**Comment by cawa-93** [comment]
Yeah. Seems contributing guide is a little outdated 😅
