### ISSUE TITLE
ERR_MODULE_NOT_FOUND when I run the installed application but the unpacked application works fine

### ISSUE THREAD

**Issue by adnanlah** [cawa-93/vite-electron-builder#1078]
**Describe the bug**

I get this error when I run the installed application:

```md
Error [ERR_MODULE_NOT_FOUND]: Cannot find package **** imported from
```

However the unpacked application works fine.

**To Reproduce**

1. You can clone my repo I created for this specific issue: https://github.com/adnanlah/vite-electron-builder-issue
2. Run `npm install`
3. Run `npm run compile`

**Expected behavior**
The app runs normally without any errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/e845e9c8-f0d2-4185-9c85-7dbacdb95bd9)

**Additional context**
What I have done in my repo is I added a new workspace package named `api` and then I exported my `fastify` server to be called from the electron backend.

**Comment by adnanlah** [comment]
Hello,

Thanks to Claude I have fixed it by adding this to electron builder config:
```ts
extraResources: [
    {
      from: "node_modules/nanoid",
      to: "node_modules/nanoid"
    }
],
```
I am not sure if this solution is the most optimal one or not but it worked and it gave a glimpse of hope after days of searching. I am not sure why did that happen, my guess is it would be because 2 versions of `nanoid` package were installed (`3.3.7` as a nested package for postcss package and `5.0.9` I just installed):

![image](https://github.com/user-attachments/assets/fa134097-24a5-44d6-905c-a07366f045aa)

Hence the `nanoid` package folder existed in the root `node_modules` folder and in the `node_modules` in the `packages/api` folder.

I would appreciate any insight about this matter.

Thanks everyone.

**Comment by cawa-93** [comment]
Due to compilation `electron-builder` truing to resolve dependency tree and copy only what is needed. In your case I suppose you need to install `api` package as dependency in backend package.

**Comment by adnanlah** [comment]
> Due to compilation `electron-builder` truing to resolve dependency tree and copy only what is needed. In your case I suppose you need to install `api` package as dependency in backend package. 

Thanks, but I believe I have it installed in the package.json as a dependency here: https://github.com/adnanlah/vite-electron-builder-issue/blob/main/packages%2Fmain%2Fpackage.json#L15 or am I doing something else wrong.

**Comment by adnanlah** [comment]
Hello, quick update: I have been trying and playing around for the whole day, trying to install different versions of different packages and so on. At the end of the day I kind of was sure it's a dependency conflict thing but I had no proof.

So I migrated to **yarn** from **npm** and it's working just fine.

I will need to keep adding things to the project and see if I get the same issue again.
