### ISSUE TITLE
npm run watch can not work

### ISSUE THREAD

**Issue by xiaohulu** [cawa-93/vite-electron-builder#109]
When I execute `npm run watch` command, the window opened, but throw below errors

![图片](https://user-images.githubusercontent.com/624517/108670992-c767cc00-751a-11eb-83a5-da3924a8d3cb.png)

vite version is `2.0.1`.

**Comment by cawa-93** [comment]
You can [fix](https://github.com/cawa-93/vite-electron-builder/commit/e9312a6396beefdfa83374e65012667bdac481a5) this.
**⚠ Warning**: This change does not meet security requirements. And it needs a different approach. I will do a thorough research and find the best solution later.

**Comment by xiaohulu** [comment]
Ok, thanks.
