### ISSUE TITLE
electron does not open on clean install

### ISSUE THREAD

**Issue by mithom** [cawa-93/vite-electron-builder#11]
after doing a clean download, all the commands run to completion. But i fail to get any electron window to open.

please help

**Comment by cawa-93** [comment]
There may be some confusion with the commands. Could you tell which commands and in what order you ran?

**Comment by mithom** [comment]
i tried running `yarn electron` (yes i use yarn instead of npm but i did not get errors)
i also tried building before running this command with `yarn build`

**Comment by cawa-93** [comment]
First of all, you should delete this line

https://github.com/cawa-93/vite-electron-builder/blob/fa0343397b47dc1f208fc3ae609a480c657118c1/package.json#L11

It starts the workflow but blocks the start of the electron. It was my mistake

**Comment by mithom** [comment]
After removing that line, running electron still doesn't work. This time because the vite server is not running (since we don't start it anymore)
trying to run watch:build:renderer however results in the following:

`$ vite serve --config ./config/renderer.vite.js
[vite] Optimizable dependencies detected:
electron-updater

[vite] Dep optimization failed with error:
Could not load url (imported by node_modules\electron-updater\out\main.js): ENOENT: no such file or directory, open '%DIR%\vite-electron-builder-main\url'
[Error: Could not load url (imported by node_modules\electron-updater\out\main.js): ENOENT: no such file or directory, open ''%DIR%\vite-electron-builder-main\url'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: ''%DIR%\\vite-electron-builder-main\\url',
  watchFiles: [ ....`

'%DIR% was originally filled in, i redacted it.
I cannot figure out why it tries to access this non-existing file.

some side experiments that will most likely solve nothing:
adding an ampty file named `url` changes the error to \crypto instead of \url

**Comment by cawa-93** [comment]
@mithom It seems that the vit is trying to optimize all dependencies, regardless of whether they are used at a particular entry point.

The built-in optimization still doesn't work very well. It cannot optimize some things that are not designed to work in the browser, hence the error.

**Comment by cawa-93** [comment]
@mithom To run in development mode, you need to run three commands in parallel:
```
npm run watch:build:main
npm run watch:build:renderer
npm run electron
```

**Comment by cawa-93** [comment]
> 
> 
> @mithom It seems that the vite is trying to optimize all dependencies, regardless of whether they are used at a particular entry point.
> 
> The built-in optimization still doesn't work very well. It cannot optimize some things that are not designed to work in the browser, hence the error.

I fixed this problem in https://github.com/cawa-93/vite-electron-builder/commit/56c4781e0c08c93a54859886c628336bb659f1ae, however, I think it still needs some refactoring and testing.

**Comment by mithom** [comment]
ah that was the issue. I'm new to vite and not really handy with all these build frameworks. trying it out as replacement for webpack.

Thanks for the assistance!

**Comment by cawa-93** [comment]
thanks for the feedback 😁
