### ISSUE TITLE
VsCode report error when use /@/use/electron to import ts file

### ISSUE THREAD

**Issue by xiaohulu** [cawa-93/vite-electron-builder#110]
Vs Code report error when use `/@/use/electron` to import ts file. Did I miss something?

![图片](https://user-images.githubusercontent.com/624517/108697488-e3309980-753d-11eb-8842-47ff48593544.png)

![图片](https://user-images.githubusercontent.com/624517/108697863-5d611e00-753e-11eb-9292-1c370e50a363.png)

**Comment by cawa-93** [comment]
I'm not 100% sure, but it seems vetur can't correctly recognize tsconfig if it's not in the root.
Try following these [instructions](https://vuejs.github.io/vetur/guide/setup.html#advanced) and create `vetur.config.js` in root and specify `projects` for each `tsonfig.json` in src.

**Comment by xiaohulu** [comment]
I create `vetur.config.js` and config projects like below, but still report errors.

```js
projects: [
      {
        root: './src/renderer',
        package: './package.json',
        tsconfig: './src/renderer/tsconfig.json',
        snippetFolder: './.vscode/vetur/snippets',
        globalComponents: [
          './src/renderer/components/**/*.vue'
        ]
      },
      {
        root: './src/main',
        package: './package.json',
        tsconfig: './src/main/tsconfig.json'
      }
    ]
```

**Comment by xiaohulu** [comment]
`/@/` in `.vue` point to root directory, 
`/@/` in `.ts` point to `src/renderer` or `src/main` directory.

**Comment by cawa-93** [comment]
Try to write to Vetur developers. I don't use VSC so I can't confidently find the cause of the problem.
