### ISSUE TITLE
Renderer process can not import electron

### ISSUE THREAD

**Issue by xiaohulu** [cawa-93/vite-electron-builder#121]
I add below code to `renderer/app.vue`

```ts
import {ipcRenderer} from 'electron';
```

then `npm run watch` report errors `index.js:4 Uncaught ReferenceError: __dirname is not defined`
`npm run compile` success, but load failed and report errors `index.html:1 Uncaught TypeError: Failed to resolve module specifier "electron". Relative references must start with either "/", "./", or "../".`

**Comment by xiaohulu** [comment]
Fixed by [Using electron API in renderer](https://github.com/cawa-93/vite-electron-builder#using-electron-api-in-renderer).

**Comment by ErriourRU** [comment]
Hey. I have the same question now. How to access to electron from vue template now right way? Fix description already removed ;(

**Comment by cawa-93** [comment]
@ErriourRU. [Docs](https://github.com/cawa-93/vite-electron-builder#using-nodejs-api-in-renderer). In `preload` you should create [global function or something](https://github.com/cawa-93/anime-library/blob/647a92eb08b1858fa6958c5ca5fd484ed00b5761/packages/preload/src/windowControls.ts#L15). And just use it in `renderer` from [global scope](https://github.com/cawa-93/anime-library/blob/647a92eb08b1858fa6958c5ca5fd484ed00b5761/packages/renderer/src/components/TitleBar/TitleBarMinimizeWindowButton.vue#L2)
