### ISSUE TITLE
[Question]How to support vue jest test

### ISSUE THREAD

**Issue by xiaohulu** [cawa-93/vite-electron-builder#135]
I want do some unit test for vue code. Is it possible to use jest to test vue alone?

**Comment by cawa-93** [comment]
I don't think the process of testing individual components should be different from that described in the Vue documentation.

**Comment by xiaohulu** [comment]
Do you have a plan to add vue jest  test support?

**Comment by cawa-93** [comment]
I'm not sure it will be useful.  Not everyone and everywhere needs Jest. If you find a good solution we could publish it as a wiki example.

**Comment by xiaohulu** [comment]
This article should be helpful for add jest test for vitejs. I add jest success.

https://webdesigntips.blog/web-design/javascript/add-testing-to-vite/

**Comment by robokozo** [comment]
> This article should be helpful for add jest test. I add jest success.
> 
> https://webdesigntips.blog/web-design/javascript/add-testing-to-vite/

I just tried this out and it failed with the following error:

```
TypeError: Cannot destructure property 'config' of 'undefined' as it is undefined.
at Object.getCacheKey (node_modules/vue-jest/lib/index.js:10:7)
```

Here is my package.json
```
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview",
    "test": "jest"
  },
  "dependencies": {
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@types/jest": "^26.0.23",
    "@vitejs/plugin-vue": "^1.2.3",
    "@vue/compiler-sfc": "^3.0.5",
    "@vue/test-utils": "^2.0.0-rc.8",
    "jest": "^27.0.5",
    "ts-jest": "^27.0.3",
    "typescript": "^4.3.2",
    "vite": "^2.3.8",
    "vue-jest": "^5.0.0-alpha.10",
    "vue-tsc": "^0.0.24"
  }
}

```

**Comment by zeknoss** [comment]
I am currently having the same issue. Is there any progress in this situation @robokozo?

**Comment by xiaohulu** [comment]
@robokozo @zeknoss  try to use vue3-jest **27.0.0-alpha.2**
