### ISSUE TITLE
error VueDX/TS: context.imports.add is not a function

### ISSUE THREAD

**Issue by mithom** [cawa-93/vite-electron-builder#142]
![image](https://user-images.githubusercontent.com/9282831/110126943-44216280-7dc5-11eb-99f4-173675abcd31.png)

this happens with a fresh clean install of this template (commit 8e181e1d7dd45311d691b7685f0e436e6ea6e2eb and earlier)

**Comment by cawa-93** [comment]
https://github.com/znck/vue-developer-experience/issues/208

**Comment by mithom** [comment]
just want to mention that this bug blocks the CI/CD, so maybe it is worth to temporarily disable it untill it is fixed, if not, at least it is documented here now ;) thx for the fast response and have a nice day

**Comment by cawa-93** [comment]
I know: https://github.com/cawa-93/vite-electron-builder/pull/133 😥

**Comment by cawa-93** [comment]
@mithom I have made some changes to the QI process. At this point, if you want to disable type checking in the renderer you can comment this line:
https://github.com/cawa-93/vite-electron-builder/blob/9047b488dcd408231609d3b313d6297cfe9d3b2c/.github/workflows/CICD.yml#L75

**Comment by cawa-93** [comment]
@vuedx/typecheck has been replaced by vue-tsc (#162)
