### ISSUE TITLE
Main file changes, can not be hot loaded

### ISSUE THREAD

**Issue by hefangxuan** [cawa-93/vite-electron-builder#146]
What did I do wrong

**Comment by cawa-93** [comment]
This is because the watch script is not finished.  When you make changes, a new file is compiled.  But this is not enough.  You must add the application restart logic for the changes to take effect.  It is this logic that is lacking - I did not have time to fix it. 😅

**Comment by cawa-93** [comment]
If you have time you may want do refactor `bin/watch.js`. PR welcome 😉

**Comment by hefangxuan** [comment]
英文水平太差，我选择使用中文😅

我的实验：
  我想使用 nodemon 实现监听
 ```
// 我的执行步骤
yarn add nodemon -D

// package.json 增加 nodemonConfig 字段，监听主进程文件变动
"nodemonConfig": {
    "ignore": [
      "src/main/**"
    ]
  }

// 将启动函数修改这样，我感觉这是比较简单的方式
function startElectron() {
  const {exec} = require('child_process');

  // const electronPath = require('electron');

  // return spawn(electronPath, [join(process.cwd(), 'dist/source/main/index.cjs.js')]);

  exec(`nodemon --exec 'electron dist/source/main/index.cjs.js'`, { cwd: process.cwd() }, (err, stdout) => {
    if(err) {
      console.log('启动报错', err);
      return;
    }
    console.log(`stdout: ${stdout}`);
  });
}
 ```

但是我遇到一个问题，修改文件 vite 并没有重新编译，我不知道错误在哪，刚接触 vite 两天...

**Comment by hefangxuan** [comment]
我修改其他文件都得到了重新启动electron

**Comment by cawa-93** [comment]
If you think that my level of Chinese is better than my level of English then you are wrong.  I don't understand Chinese at all, so please continue speaking English

**Comment by hefangxuan** [comment]
Modify src/main.ts Failed to build. What's the problem? Your default project has this problem
