### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by autumnalriver** [cawa-93/vite-electron-builder#168]
**Describe the bug**
When the script `compile` is executed, the result tell me failed.

**To Reproduce**
1. Go to the command line
2. Execute the script `compile`
3. The pack process is terminated
4. Says that asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available

**Expected behavior**
The script executes successfully and the *Setup* package file is generated.

**Screenshots**
D:\repos\electronjs\vite-electron-builder-main>npm run compile

> vite-electron-builder@ precompile D:\repos\electronjs\vite-electron-builder-main
> cross-env MODE=production npm run build

> vite-electron-builder@ build D:\repos\electronjs\vite-electron-builder-main
> node scripts/build.js

packages/main/
  vite v2.1.2 building for production...
transforming (148) ..\..\node_modules\balanced-match\index.js  'default' is imported from external module 'util' but never used
  ✓ 151 modules transformed.
  dist/index.cjs   3.02kb / brotli: 1.12kb
  dist/index.cjs.map 5.46kb
  Bundling time: 2.639s

packages/preload/
  vite v2.1.2 building for production...
  ✓ 1 modules transformed.
  dist/index.cjs   0.18kb / brotli: 0.13kb
  dist/index.cjs.map 1.46kb
  Bundling time: 108.418ms

packages/renderer/
  vite v2.1.2 building for production...
  ✓ 24 modules transformed.
  dist/logo.03d6d6da.png    6.69kb
  dist/index.html           0.46kb
  dist/index.ff4157e8.css   0.26kb / brotli: 0.15kb
  dist/About.cb2527ca.js    0.57kb / brotli: 0.32kb
  dist/About.cb2527ca.js.map 1.08kb
  dist/About.1ce46fba.css   0.07kb / brotli: 0.05kb
  dist/index.fb3e6a07.js    2.41kb / brotli: 1.07kb
  dist/index.fb3e6a07.js.map 5.67kb
  dist/vendor.d30bbbfa.js   64.26kb / brotli: 22.58kb
  dist/vendor.d30bbbfa.js.map 629.17kb
  Bundling time: 4.559s

Total bundling time: 7.313s

> vite-electron-builder@ compile D:\repos\electronjs\vite-electron-builder-main
> electron-builder build --config electron-builder.config.js --dir --config.asar=false

  • electron-builder  version=22.10.5 os=10.0.19042
  • loaded configuration  file=D:\repos\electronjs\vite-electron-builder-main\electron-builder.config.js
  • description is missed in the package.json  appPackageFile=D:\repos\electronjs\vite-electron-builder-main\package.json
  • author is missed in the package.json  appPackageFile=D:\repos\electronjs\vite-electron-builder-main\package.json
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.1 appOutDir=dist\win-unpacked
  • Unpacking electron zip  zipPath=undefined
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available

**Additional context**
- Windows 10.0.19042.870 Pro x64
- NodeJS 14.16.0
- Windows Terminal 1.6.10571.0

**Comment by cawa-93** [comment]
This is not a bug, this is a feature.

> In npm script `compile`: This script is configured to compile the application as quickly as possible. It is not ready for distribution, is compiled only for the current platform and is used for debugging.

[The `compile` script has two arguments](https://github.com/cawa-93/vite-electron-builder/blob/0a237ba959c88a6f6e78ecb1bcf4732644768b6c/package.json#L13):

- `--dir` - Disables the creation of installers. But you will still have ready-to-run `win-unpacked` application. This reduces compilation time and is useful for testing.
- `--config.asar=false` -  This disables archiving to Asar. All files in your application will be as is, without additional archives. This reduces compilation time and is useful for testing.

**Comment by autumnalriver** [comment]
Thanks for your explanation.
