### ISSUE TITLE
Somehow get the `node` and `chrome` versions  at the `build` time

### ISSUE THREAD

**Issue by cawa-93** [cawa-93/vite-electron-builder#208]
I want to somehow get the `node` and `chrome` versions that are sewn into the electron, and pass those versions to the `esbuild` config and `browserslist` config.

The following solution is currently in use:
[Separate workflow](https://github.com/cawa-93/vite-electron-builder/blob/8a5aa5b4debf66300cddb5c5bcc0bd99ae5b4c02/.github/workflows/update-electron-vendors.yml) has been update [`electron-vendors.config.json`](https://github.com/cawa-93/vite-electron-builder/blob/8a5aa5b4debf66300cddb5c5bcc0bd99ae5b4c02/electron-vendors.config.json) and [`.browserslistrc`](https://github.com/cawa-93/vite-electron-builder/blob/8a5aa5b4debf66300cddb5c5bcc0bd99ae5b4c02/.browserslistrc) files on push to main branch.

I would like to receive the versions directly at the `build` time.

**Comment by JoCat** [comment]
What exactly is the problem?

**Comment by cawa-93** [comment]
Node and chromium versions must be transferred to all dependent configurations. For example
https://github.com/cawa-93/vite-electron-builder/blob/fa1f14b34db09128178a46249858551c98956b0c/packages/main/vite.config.js#L23
https://github.com/cawa-93/vite-electron-builder/blob/fa1f14b34db09128178a46249858551c98956b0c/packages/renderer/vite.config.js#L31
https://github.com/cawa-93/vite-electron-builder/blob/8a5aa5b4debf66300cddb5c5bcc0bd99ae5b4c02/.browserslistrc#L1

A [special file](https://github.com/cawa-93/vite-electron-builder/blob/8a5aa5b4debf66300cddb5c5bcc0bd99ae5b4c02/electron-vendors.config.json) is being created now, but I would like to get this information dynamically at compile time. The most pressing problem with browserslist: I do not know how it is possible to dynamically set the version of chromium so that all packages as that postcss correctly received this information.

I think the issue in the electron repository may be a bit outdated because I found a workaround, but it doesn't work fast enough.

**Comment by JoCat** [comment]
@cawa-93 Well, in fact, you can implement a call to get a version at the build stage (at least in the vite config for sure)
The problem as I see it is mainly that the electron does not give the chromium version when running in node node.js
By the way, electron seems to have a REPL, maybe it will help us somehow, but here's the problem, it doesn't work on Windows

**Comment by cawa-93** [comment]
Chrome version i got from V8 version

https://github.com/cawa-93/vite-electron-builder/blob/fa1f14b34db09128178a46249858551c98956b0c/scripts/update-electron-vendors.js#L31

**Comment by JoCat** [comment]
> Chrome version i got from V8 version
> 
> https://github.com/cawa-93/vite-electron-builder/blob/fa1f14b34db09128178a46249858551c98956b0c/scripts/update-electron-vendors.js#L31

Ещё раз проверил этот момент и да, как оказалось, последние релизы хрома совпадают с версией v8 (и blink)
https://en.wikipedia.org/wiki/Google_Chrome_version_history

In principle, you can define a set of functions to get versions, and call them when building in the vite config (for example, just like path() calls)
But I don’t know about .browserslistrc, you can, in principle, just as with the build, just call the rewriting of the file

**Comment by cawa-93** [comment]
Actually `browserslistrc` is the biggest problem 🤷‍♂️

**Comment by JoCat** [comment]
I'll try to come up with something tonight 🤔

**Comment by JoCat** [comment]
For example:
https://github.com/JoCat/vite-electron-builder/blob/a3a6c8da09ddffb6def2cc8d8ea5f3d16e00c67f/scripts/update-electron-vendors.js#L65-L73
https://github.com/JoCat/vite-electron-builder/blob/a3a6c8da09ddffb6def2cc8d8ea5f3d16e00c67f/packages/main/vite.config.js#L4-L6
https://github.com/JoCat/vite-electron-builder/blob/a3a6c8da09ddffb6def2cc8d8ea5f3d16e00c67f/packages/main/vite.config.js#L25
https://github.com/JoCat/vite-electron-builder/blob/a3a6c8da09ddffb6def2cc8d8ea5f3d16e00c67f/packages/renderer/vite.config.js#L7-L9
https://github.com/JoCat/vite-electron-builder/blob/a3a6c8da09ddffb6def2cc8d8ea5f3d16e00c67f/packages/renderer/vite.config.js#L34

**Comment by cawa-93** [comment]
@JoCat What about browserlist, postcss?

**Comment by JoCat** [comment]
> @JoCat What about browserlist, postcss?

You can also call functions and write files before the build

**Comment by JoCat** [comment]
https://github.com/JoCat/vite-electron-builder/commit/2d4e7608fbb82d19367b943c0bb74a518e8c44a1

**Comment by jsheffers** [comment]
Can you guys drop the link to the Electron issue mentioned in this thread, I'm curious as to why the vendor's config is even needed?

**Comment by JoCat** [comment]
> Can you guys drop the link to the Electron issue mentioned in this thread, I'm curious as to why the vendor's config is even needed?

https://github.com/electron/electron/issues/28006

**Comment by Kilian** [comment]
`browserslist` also supports Electron directly through [electron-to-chromium](https://www.npmjs.com/package/electron-to-chromium), and [electron-releases](https://www.npmjs.com/package/electron-releases) gives you the Node version for each Electron version.

**Comment by JoCat** [comment]
@cawa-93 
Following the example from the comment https://github.com/electron/electron/issues/28006#issuecomment-1035985137
Updated the code. It works. https://github.com/JoCat/vite-electron-builder/commit/37b694d8baa23278ff3e39bd37a3063b64324e4c

**Comment by cawa-93** [comment]
@JoCat Seems you did the same thing just split it into two files. I would like to abandon the launch of the electron instance altogether.

**Comment by JoCat** [comment]
> @JoCat Seems you did the same thing just split it into two files. I would like to abandon the launch of the electron instance altogether.

I agree, this is annoying (because the launch of an electron also takes some time)
