### ISSUE TITLE
how can i use nodejs in render process ?

### ISSUE THREAD

**Issue by liu1435533520** [cawa-93/vite-electron-builder#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liu1435533520** [comment]
when i use require in render process ,it throw a Error !

**Comment by cawa-93** [comment]
- https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content
- https://github.com/cawa-93/vite-electron-builder#using-electron-api-in-renderer
- https://github.com/cawa-93/vite-electron-builder/issues/76#issuecomment-803600966
