### ISSUE TITLE
Automatically infer type of exposed api in preload

### ISSUE THREAD

**Issue by usernamehw** [cawa-93/vite-electron-builder#266]
A minor tweak to not duplicate code for types:

https://github.com/cawa-93/vite-electron-builder/blob/d4d7c738646475357449a069330d8d334284f6b8/packages/preload/src/index.ts#L7-L9

Becomes:

```ts
export const api = {
  versions: process.versions,
};
```

---

https://github.com/cawa-93/vite-electron-builder/blob/d4d7c738646475357449a069330d8d334284f6b8/packages/preload/types/electron-api.d.ts#L1-L9

Becomes:

```ts
declare interface Window {
	electron: Readonly<typeof import('../src/index').api>;
	electronRequire?: NodeRequire;
}
```

Not sure if there are any drawbacks.

**Comment by cawa-93** [comment]
I used [similar](https://github.com/cawa-93/vite-electron-builder/blob/3fbfb2ce0cd00fdebc20ac339563382dc287f5bb/src/preload/index.ts#L7-L12) decision, but I gave it up. The fact is that the renderer must import the type from the preload. And make it easier as it is now. There were some problems with this. But I don't remember exactly which ones.

**Comment by usernamehw** [comment]
Ok.
