### ISSUE TITLE
Link to fixed issue

### ISSUE THREAD

**Issue by usernamehw** [cawa-93/vite-electron-builder#267]
https://github.com/cawa-93/vite-electron-builder/blob/d4d7c738646475357449a069330d8d334284f6b8/packages/main/src/index.ts#L15-L19

The linked issue seems to be solved in TypeScript **4.2.0** which this package already uses.

**Comment by cawa-93** [comment]
[Nope](https://www.typescriptlang.org/play?allowUnreachableCode=true&importHelpers=true&target=99&jsx=0&ts=4.2.3#code/CYUwxgNghgTiAEAXAngBwamB7YBXMiAllgHYCiJAbvALzwDeARALIDyAImYwFyOY74ipRgF8AUKEiwEKdPFCUQELKgC2IEogrU6TNpx6MFSles2iJ4aHCRoEASVWosMRMxCIo22vH54CxORU8AA+8iCKymoaWlRillI2AObKAEZQEAxi8PCEmiAwAGZQYA5OLm4eUFk5ORqU3PCOzq7untoA3Nnw4uJihbgkAaS+2MCsJBDIABRQjQDkfoKB8wCUDOIDQ0Ik4ZQTU7MLxlFmiGsb8fGEhfDThOWuAHTqnk-1T-pktDR0i2PLUgXejdPwHGYPFqIF5Vd5UT4cMjrAD0yPgZBg2BgYj6NzukIqMLeHy+Pz+J1MMWB3QU4Puj2hrygcMoCM4KLRGKxOKuYFIAGdEPB6j4Cc8mSz4Kj4AApXCC+BgOBQRAIDKEKD8663aYkxFk+D-ATDEjUnJgyYzPXsqVo1gAax5YjxuvhpN+5IiJmimjNezp1qRtvgDpxQA). Solved in 4.3

**Comment by usernamehw** [comment]
Weird. The issue has 4.2 milestone... https://github.com/microsoft/TypeScript/issues/41468
