### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Dreaming-Codes** [cawa-93/vite-electron-builder#320]
**Describe the bug**
Unable to create an app with transparency

**To Reproduce**
1. Go to [this line](https://github.com/cawa-93/vite-electron-builder/blob/2a5e5437f4f95225b6a218a9d9d9c3afa8dd95c7/packages/main/src/index.ts#L38)
2. Add this transparent: true,
3. Run npm run watch

**Expected behavior**
The app starts normally

**Screenshots**
![image](https://user-images.githubusercontent.com/10401566/124036316-1a3c1d80-d9fe-11eb-9d37-b809e33baec3.png)

**Comment by cawa-93** [comment]
From [electron docs](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions):

> `transparent` Boolean (optional) - Makes the window transparent. Default is false. On Windows, does not work unless the window is frameless.
