### ISSUE TITLE
Add `npx degit` instruction

### ISSUE THREAD

**Issue by bato3** [cawa-93/vite-electron-builder#323]
Currently github has a bug that in case I'm not logged in `/ generate` shows 404. Can you add an alternate usage method in the readme: `npx degit`?

Thanks

**Comment by cawa-93** [comment]
I do not fully understand what the problem is and how it relates to this template.

**Comment by bato3** [comment]
I was not logged in, github showed me 404. At first, I wanted to report that this link does not work. ;)

I was just surprised by the error when I used this [link](https://github.com/cawa-93/vite-electron-builder/blame/main/README.md#L30). (Especially since the `clone` button is shown for guests instead of` generate`. )

I know this is nonsense: fixing an engine error in app code... 

In summary: if an alternative method of using a template were given, I wouldn't have wasted an hour.
