### ISSUE TITLE
Can't  read property 'Glob' of undefind

### ISSUE THREAD

**Issue by t-sinbo** [cawa-93/vite-electron-builder#346]
**Describe the bug**
clone the framework  and yarn install,the app runs successfully,but there is a error

**To Reproduce**
1. clone
2. yarn install

**Expected behavior**
No any problem

**Screenshots**
![image](https://user-images.githubusercontent.com/30678067/126293005-bebac194-e0b1-4eaa-8cc9-e3bebc5c500b.png)

**Comment by cawa-93** [comment]
Try use `npm`  v >7.7 to install dependencies and run script:
```bash
npm ci && npm run watch
```

This is needed to find out if this is a problem with the dependencies or with package manager.

**Comment by t-sinbo** [comment]
> Try use `npm` v >7.7 (I use 7.18.1) to install dependencies and run script:
> 
> ```shell
> npm ci && npm run watch
> ```
> 
> This is needed to find out if this is a problem with the dependencies or with package manager.

I tried to use npm 14.x and 8.x,but it's does't work

**Comment by cawa-93** [comment]
Try add `'electron-devtools-installer'` to `build.rollupOptions.external` in `packages/main/vite.config.js`

I managed to reproduce the problem, but only from the yarn. After installing dependencies by NPM, the problem disappears for me.

**Comment by seanaye** [comment]
After importing other dependencies to my project this error prevents electron process from starting. Im guessing this means that I need to add my dependencies to the the `build.ollupOpions.external` but its not clear what needs to be added. The error message does not mention any specific package names. I even tried to read the bundled code but its still not obvious what package triggers the error. 

Is there any way to be more explicit with this error so I can know what packages cause it? Or is it an upstream issue with Vite?

**Comment by cawa-93** [comment]
@seanaye The problem above is that Vite is designed to optimize the packages that should work in the browser. And it can't always optimize packages that have a node-specific architecture.

I don't see an easy way to detect a problem package other than to gradually add / remove them to the `build.rollupOptions.external` list and check for a problem.

**Comment by seanaye** [comment]
@cawa-93 Thanks for your support on this template, I have become a backer on open collective and I would encourage others to do the same if possible
