### ISSUE TITLE
Preload API crashes renderer

### ISSUE THREAD

**Issue by aleksey-hoffman** [cawa-93/vite-electron-builder#474]
**Describe the bug**
When I add `env` object to preload API, it crashes the renderer window:

#### `packages\preload\src\index.ts`
```js
const api: ElectronApi = {
  env: process.env,
  versions: process.versions,
}
```

#### `packages\preload\types\electron-api.d.ts`
```js
interface ElectronApi {
  readonly versions: Readonly<NodeJS.ProcessVersions>;
  readonly env: Readonly<NodeJS.ProcessEnv>;
}
```

I'm new to Typescript. Am I doing something wrong?

If I serialize the object, it works:

```js
const api: ElectronApi = {
  env: JSON.stringify(process.env),
  versions: process.versions,
}
```

But then I'd have to parse it in the renderer and declare `env` as a string type, which doesn't make sense.
What can be causing the problem?

**To Reproduce**
1. Clone `vite-electron-builder` and add the code above to specified files
2. npm run watch

**Comment by cawa-93** [comment]
There are not point for TS. `process.env` can't be serialized. [Read this](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception).

You should convert Node.js object to regular JS Object. For example:
```js
const api: ElectronApi = {
  env: {...process.env},
  versions: process.versions,
}
```

**Comment by aleksey-hoffman** [comment]
@cawa-93 thanks, it worked, however TS shows an error:
Can you please suggest a solution for this?

![image](https://user-images.githubusercontent.com/61761672/135923660-ffc3ec8b-7cde-4d2d-bc81-a073fdfef36c.png)

![image](https://user-images.githubusercontent.com/61761672/135923904-f6816930-2984-4d7f-b13b-3daa9bd2557e.png)

**Comment by aleksey-hoffman** [comment]
@cawa-93 thanks, it worked, however TS shows an error:
Can you please suggest a solution for this?

![image](https://user-images.githubusercontent.com/61761672/135923660-ffc3ec8b-7cde-4d2d-bc81-a073fdfef36c.png)

![image](https://user-images.githubusercontent.com/61761672/135923904-f6816930-2984-4d7f-b13b-3daa9bd2557e.png)

Also, why is the `versions: process.versions` working without the conversion `versions: {...process.versions}`? They are both objects, aren't they?
