### ISSUE TITLE
Warnings when starting watch on freshly cloned template

### ISSUE THREAD

**Issue by Uninen** [cawa-93/vite-electron-builder#492]
**Describe the bug**

`npm run watch` produces the following warnings when running after cloning this template and installing deps:

```
> watch
> node scripts/watch.js

14:27:18 [main] (node:68741) ExtensionLoadWarning: Warnings loading extension at /Users/uninen/Library/Application Support/vite-electron-template/extensions/ljjemllljcmogpfapbkkighbhhppjdbg:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `Electron --trace-warnings ...` to show where the warning was created)
```

**To Reproduce**
1. Clone the project
2. Run `npm install`
3. Run `npm run watch`

**Expected behavior**

No warnings.

**Comment by cawa-93** [comment]
Relevant:
https://github.com/MarshallOfSound/electron-devtools-installer/issues/143

**Comment by Uninen** [comment]
Ok, thanks! 👍 

This may be worth documenting. I'm new to Electron so didn't know where to look for further info :)

**Comment by cawa-93** [comment]
@udondan Sounds good
