### ISSUE TITLE
Refuse to use commonjs modules in favor of esm

### ISSUE THREAD

**Issue by cawa-93** [cawa-93/vite-electron-builder#50]
### Benefits:
This will not provide any performance enhancement or any other technical benefits.

### Goal:
unify the system of modules throughout the project, regardless of the language and runtime environment.

### Blocked:
The electron is currently working very poorly with esm. In addition, there is a share of modules that can not work with esm syntax.

### Related:
- https://github.com/electron/electron/issues/21457

**Comment by awkj** [comment]
I hate commonjs, but I have no way to go from node to electron

**Comment by cawa-93** [comment]
There are also problems with the electron builder, eslint.

**Comment by danieledler** [comment]
Maybe this can help? https://github.com/xiaoxiangmoe/vite-plugin-commonjs-externals

> Add commonjs external support for vite. Mainly to provide vite support for electron.

**Comment by cawa-93** [comment]
@danieledler The main obstacle is not vite. The electron does not support the ESM system in runtime very well.

**Comment by cawa-93** [comment]
https://github.com/electron/electron/issues/21457#issuecomment-1099904505

**Comment by cawa-93** [comment]
Re check this after electron v28 released

**Comment by raphaelmenges** [comment]
There is also a new major release 5 of Vite that might require the shift to ESM: <https://vitejs.dev/guide/migration.html#deprecate-cjs-node-api>

**Comment by cawa-93** [comment]
https://github.com/cawa-93/vite-electron-builder/discussions/974
