### ISSUE TITLE
npm run watch (TypeError: Cannot read properties of undefined (reading 'requestSingleInstanceLock'))

### ISSUE THREAD

**Issue by fulus06** [cawa-93/vite-electron-builder#554]
![image](https://user-images.githubusercontent.com/12890684/141417007-76984af6-552f-4523-8df7-8e249323feb1.png)

**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'requestSingleInstanceLock')

**To Reproduce**
1. npm install
2. npm run watch
`下午1:45:04 [main] /workspace/normojs/korvo-browser/packages/main/dist/index.cjs:27
const isSingleInstance = require$$1.app.requestSingleInstanceLock();
TypeError: Cannot read properties of undefined (reading 'requestSingleInstanceLock')`

**Comment by cawa-93** [comment]
Strange. Could you check your code on another OS? I checked the last commit on Windows and did not notice any problems

**Comment by dharmaturtle** [comment]
I can't recreate this error either on Windows with the latest master. Might I suggest you ensure you're either on a fresh clone or run [`git clean -xdf`](https://tysonwilliams.coding.blog/2020-07-11_systematic_cleaning#git-clean--fdx).

**Comment by fulus06** [comment]
No problem in Win10
![企业微信截图_16369643674709](https://user-images.githubusercontent.com/12890684/141759700-7f9da4f2-91c6-43c1-a296-4bb5d8ca3375.png)

**Comment by cawa-93** [comment]
@fulus06 Is this still relevant?

**Comment by RichardKanshen** [comment]
Recently tried this setup. Happening to me on Windows 11, Electron 35.1.5, nodemon 3.1.9

![Image](https://github.com/user-attachments/assets/53559d27-d5ad-4a71-b150-08402a53ce75)

The app does not crash, and the singleInstanceLock works, it just errors.
