### ISSUE TITLE
Make the template IDE independent

### ISSUE THREAD

**Issue by HermanLederer** [cawa-93/vite-electron-builder#556]
**Is your feature request related to a problem? Please describe.**
Currently the template has IntelliJ IDEA settings built in. I think it would be more convenient for people not to have it in the template, especially if they use a different editor.

**Describe the solution you'd like**
1. Remove /.idea
1. Add .idea and .vscode to .gitignore

I can make a PR with this if the author agrees

**Comment by cawa-93** [comment]
This template also contains some [configuration for the VS code](https://github.com/cawa-93/vite-electron-builder/issues/110). 🤷‍♂️ If comfortable work with the project requires additional IDE settings, then it is logical to distribute these settings in the template.
