### ISSUE TITLE
It appears that the Vetur config doesn't work well with Vetur v0.35.0?

### ISSUE THREAD

**Issue by benlesh** [cawa-93/vite-electron-builder#595]
**Describe the bug**

First: Why I'm filing this bug _here_. As a new-to-Vue user, I wasn't sure what in the world was going on here. I was unfamiliar with Vetur and I had to spend some time debugging the issue. While it's arguable that this is a problem with Vetur, it's definitely a distraction from getting started with Vue-in-electron fun, and I think it would be a good idea for this project to shield new users from errors unrelated to the content of the project. I think I'd recommend commenting out that line in the vetur config. (It might even be nice for new users if there was some comment documenting what in the world the Vetur config is, and/or what they should know about it)

With a fresh clone of this repo, using the latest VS Code and the latest Vetur extension (at the time of the writing). I'm getting a TON of errors (aka "red squigglies") until I disable the experimental template interpolation.

**To Reproduce**
1. clone the repo
2. npm install
3. Open in VS code with the latest Vetur installed (v0.35.0)

**Expected behavior**
No errors in the IDE.

**Screenshots**
![image](https://user-images.githubusercontent.com/1540597/144125347-e80b8903-8a00-4a56-b852-cad2ada85ce9.png)

**Additional context**

- OS: Windows 10
- VS Code:
  - Version: 1.62.3 (user setup)
  - Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
  - Date: 2021-11-17T08:11:14.551Z
  - Electron: 13.5.2
  - Chrome: 91.0.4472.164
  - Node.js: 14.16.0
  - V8: 9.1.269.39-electron.0
  - OS: Windows_NT x64 10.0.19042
- Vetur Extension version 0.35.0

**Workaround**

For now, simply commenting out `'vetur.experimental.templateInterpolationService': true` and running the VS Code command `Vetur: Restart VLS` will resolve the issue. However, I don't get types in the template.

**Comment by benlesh** [comment]
I've filed a related bug in Vetur (as Github linked above), here: https://github.com/vuejs/vetur/issues/3257

**Comment by cawa-93** [comment]
cc @xiaohulu

**Comment by Peeterush** [comment]
Vetur doesn't seem to play well with typescript 4.5, see vuejs/vetur#3244

**Comment by Uninen** [comment]
FWIW Vetur is no longer the officially supported IDE extension for Vue 3. [Volar](https://github.com/johnsoncodehk/volar) is [officially recommended](https://v3.vuejs.org/api/sfc-tooling.html#ide-support) and works great w/ TypeScript as well. 

(I'm not affiliated in any way. I maintain vite-ts-tailwind-starter template and have been using both of these for a long time. Switched fully to Volar about a year ago, it's *much* better w/ Vue 3.)

**Comment by xiaohulu** [comment]
Thanks @Uninen，I will switch to Volar too.

**Comment by cawa-93** [comment]
This is like a mistake in Vitur. For now, I'll close it.
