### ISSUE TITLE
Eslint not working

### ISSUE THREAD

**Issue by zSakuraEvilz** [cawa-93/vite-electron-builder#602]
**Describe the bug**
Eslint not working

**To Reproduce**
1. npm install
2. Edit packages/main/src/index.ts
3. npm run lint

**Expected behavior**
Eslint will show error.

**Screenshots**
![image](https://user-images.githubusercontent.com/9639276/144620741-20651c91-d780-4828-92b6-59bf52d5edc9.png)

**Comment by cawa-93** [comment]
Upstream
https://github.com/typescript-eslint/typescript-eslint/issues/3950
