### ISSUE TITLE
Can not work with node-opcua

### ISSUE THREAD

**Issue by StormBlue** [cawa-93/vite-electron-builder#613]
English is not my native language; please excuse typing errors.

**Describe the bug**
I am developing an opc-ua client.After install node-opcua and import it in preload.ts,the project reports an error.

**To Reproduce**
1. git clone https://github.com/cawa-93/vite-electron-builder.git
2. cd "vite-electron-builder"
3. npm install
4. npm install node-opcua
5. edit preload/src/index.ts
`import {
  OPCUAClient,
} from "node-opcua-client";`
`console.log(OPCUAClient);`
6. npm run watch

**Expected behavior**
No error is reported, logs are printed normally.

**Screenshots**
<img width="917" alt="1639041758(1)" src="https://user-images.githubusercontent.com/8924283/145369043-ad9f31a6-e89e-46eb-8f5b-b0ec3930cb94.png">

**Additional context**
But When i use [electron-quick-start-typescript](https://github.com/electron/electron-quick-start-typescript),node-opcua works fine.
So I guess it’s a problem with code compilation.I tried for a long time, but didn't find a solution.

**Comment by cawa-93** [comment]
Try add `node-opcua-client` to `build.rollupOptions.external` in `packages/preload/vite.config.js`

**Comment by StormBlue** [comment]
> Try add `node-opcua-client` to `build.rollupOptions.external` in `packages/preload/vite.config.js`

It works,thank you very much.
This project helped me solve many problems.
Wish you a nice day.

**Comment by StormBlue** [comment]
> Try add `node-opcua-client` to `build.rollupOptions.external` in `packages/preload/vite.config.js`

It works,thank you very much.
This project helped me solve many problems.
Wish you a nice day.
