### ISSUE TITLE
Watch script ignores configuration of renderer/vite.config.js

### ISSUE THREAD

**Issue by maximilize** [cawa-93/vite-electron-builder#625]
**Describe the bug**
We are using the `vite-electron-builder` template together with `react-native-web`. Building works fine, but the watch script does not work as expected.

Many react-native libs do not use `.jsx` as file extension for JSX files, they just use `.js`. The metro bundler which is used by react-native is fine with this. For vite we needed to add this config to the renderer:
```js
  esbuild: {
    loader: 'tsx',
    include: [/(src|react-native-.*)\/.*\.[tj]sx?$/],
    exclude: [],
  },
```

This way, also `.js` files get treated as `.jsx`. However, it seems that the watch script is ignoring the `packages/renderer/vite.config.js` configuration.

**To Reproduce**
1. Create a project based on vite-electron-builder
2. Create a JSX component with the file extension `.js`
3. Add the `esbuild` config to `packages/renderer/vite.config.js`
4. Run `npm run watch`
5. See error

**Comment by cawa-93** [comment]
If the configuration was ignored, the application would not run at all.

By default, Vite sets the [following configuration](https://github.com/vitejs/vite/blob/aab303f7bd333307c77363259f97a310762c4848/packages/vite/src/node/plugins/esbuild.ts#L165-L168).

Note that it set `.js` as `exclude`

Therefore, you must reset the exclude. Something like below should work
```js
  esbuild: {
    loader: 'tsx',
    include: [/(src|react-native-.*)\/.*\.[tj]sx?$/],
    exclude: [],
  },
```

**Comment by maximilize** [comment]
Actually we use the `exclude: []` config. I just removed it in my first post because I thought it was a mistake on our side. We have this issue since we started to use vite a few months ago. I already tried to find a solution for a few hours, but failed.

I'll edit my first post to reflect our exact situation.

**Comment by cawa-93** [comment]
Please, Provide a minimum reproduction and what error you are getting

**Comment by maximilize** [comment]
I created a branch to demonstrate the error: https://github.com/maximilize/vite-electron-builder/tree/react-error-demo

To run this:
1. `git clone git@github.com:maximilize/vite-electron-builder.git`
2. `cd vite-electron-builder`
3. `git checkout react-error-demo`
4. npm i
5. npm run watch
6. npm run build

The `watch` command will fail, the `build` command will succeed. At least on my side. Somehow it was tricky to reproduce this error inside this repo. However, this error always happens in our app, even after I copy+pasted the relevant files 1:1.

Sorry, I forgot to include the error before, here you go:

```
$ npm run watch

> vite-electron-builder@ watch /home/projects
> node scripts/watch.js

 > packages/renderer/src/App.js:4:9: error: Unexpected "<"
    4 │   return <h1>Hello bugs!</h1>;
      ╵          ^

Error: Build failed with 1 error:
packages/renderer/src/App.js:4:9: error: Unexpected "<"
    at failureErrorWithLog (/home/projects/node_modules/esbuild/lib/main.js:1493:15)
    at /home/projects/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/home/projects/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/projects/node_modules/esbuild/lib/main.js:1149:7)
    at /home/projects/node_modules/esbuild/lib/main.js:1258:14
    at /home/projects/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/projects/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/projects/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Unexpected "<"'
    }
  ],
  warnings: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vite-electron-builder@ watch: `node scripts/watch.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vite-electron-builder@ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2021-12-17T15_06_50_442Z-debug.log
```

I already wrote in my first post how to reproduce this error.

**Comment by cawa-93** [comment]
Were you able to adjust the desired behavior in the clean Vite project (using `npm init vite@latest`)?

I think this is upstream issue. Vite set esbuild loader based on file extension
https://github.com/vitejs/vite/blob/7ed870273206b5e9dcedda6f0149b7b3324dea45/packages/vite/src/node/optimizer/scan.ts#L438

**Comment by maximilize** [comment]
Here a very minimal version of my demo code which only has the bare minimum on modules installed: https://github.com/maximilize/vite-electron-builder/tree/react-vite-only

All packages are up to date, the same error happens again. `npm run build` works (it handles the `esbuild` config correctly), `npm run watch` fails.

**Comment by cawa-93** [comment]
@maximilize I think you should open the issue in the Vite Repository. For now, I'll close it.
