### ISSUE TITLE
yarn install warning

### ISSUE THREAD

**Issue by starzou** [cawa-93/vite-electron-builder#632]
➜  vite-electron-builder git:(main) yarn
yarn install v1.22.17
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@5.8.0" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 88.12s.

**Comment by cawa-93** [comment]
> Note: This template uses npm v7 feature — Installing Peer Dependencies Automatically. If you are using a different package manager, you may need to install some peerDependencies manually.
