### ISSUE TITLE
Bug with eslint

### ISSUE THREAD

**Issue by WhiteBite** [cawa-93/vite-electron-builder#650]
![image](https://user-images.githubusercontent.com/19576772/147878832-eb190d13-7b52-4182-99c0-52609aea7ee5.png)
I can`t configure this in IDEA =(
Maybe it`s wrong settings in project?

**Comment by cawa-93** [comment]
What package manager you used?

**Comment by WhiteBite** [comment]
npm

**Comment by WhiteBite** [comment]
I fixed this by running command
`npm install typescript --save-dev`
