### ISSUE TITLE
Main package should be compiled for node env

### ISSUE THREAD

**Issue by quolpr** [cawa-93/vite-electron-builder#655]
I had an issue with the axios library when I was using axios in the main package, the code was resolving to the XHR adapter. It was happening due to this field in package.json of axios:

```
  "browser": {
    "./lib/adapters/http.js": "./lib/adapters/xhr.js"
  },
```

It means that for browser env `./lib/adapters/http.js` file should be replaced with `./lib/adapters/xhr.js`, but main package is running under node environment, and it was causing the error. Here is the more detailed issue https://github.com/vitejs/vite/issues/6382 .

So, I fixed it with `ssr: true` in the build section of config.vite.js. What do you think about this? I can provide PR if you want 🙂

**Comment by quolpr** [comment]
Oops, the electron app will not work after compilation when `ssr: true` is provided; it fails to resolve dependencies(cause `ssr: true` doesn't bundle all deps to one file). So I am not sure how we could fix it 🤔 But we need to let vite know that it is running in node env for the main package

**Comment by quolpr** [comment]
Also related issue https://github.com/vitejs/vite/issues/4405

**Comment by cawa-93** [comment]
Hmmm...
Try add axios to external packages. That axios should resolve in runtime in electron environment

**Comment by quolpr** [comment]
Wow, thanks for the fast response, I will check 🙂 Also related https://github.com/axios/axios/issues/456

**Comment by quolpr** [comment]
@cawa-93 this error happens when I running the compiled version

![image](https://user-images.githubusercontent.com/7958527/148127612-73fa507a-b8cc-4245-ae79-12f130d86e36.png)

The `yarn watch` works like a charm

**Comment by quolpr** [comment]
Btw I am getting the same error for `ssr: true` for compiled version, while `yarn watch` works correctly

**Comment by cawa-93** [comment]
🤔 I just tried run compilation with `ssr: true` and doesn't saw problems

**Comment by cawa-93** [comment]
It seems you can import axios from relative path:
```ts
import axios from '../../../node_modules/axios';
```

That force Vite does't resolve `browser` mapping and resolve only as node. I'm not sure how safe it is 🤷‍♂️

**Comment by quolpr** [comment]
Oops, I used yarn workspaces, and that what the reason why some node packages were not loaded. Btw, I still think that the main package should use `ssr: true`, cause I suppose you will fail to use any native package(that uses gyp). As I understand later Vite will introduce this flag:

```
{
  resolve : {
    environment: 'node'
  }
}
```

**Comment by cawa-93** [comment]
> Btw, I still think that the main package should use `ssr: true`,

You may be right. But I need more tests and research for that change

**Comment by cawa-93** [comment]
It seems build in `ssr: true` works fine for `main` and `preload`. But I can't dare use it because SSR support is still experimental.

**Comment by cawa-93** [comment]
Should be resolve in https://github.com/cawa-93/vite-electron-builder/commit/d002d6f2267418407d173e538e3792e012a67415
