### ISSUE TITLE
How to use with serialport?

### ISSUE THREAD

**Issue by Minori-ty** [cawa-93/vite-electron-builder#658]
how to use with serialport? it need  node env. I want the electron-builder don't resolve serialport such as webpack externals
![image](https://user-images.githubusercontent.com/79521943/148149242-3f696b80-b429-4d11-8367-0a60209a7a32.png)
here is the demo that I use serialport with vue-cli:
https://github.com/Minori-ty/vue-cli-vue3-electron-serialport.git
you can see the config in the vue.config.js

**Comment by cawa-93** [comment]
Duplicate https://github.com/cawa-93/vite-electron-builder/discussions/657
