### ISSUE TITLE
How to use with file-type

### ISSUE THREAD

**Issue by vinchilive** [cawa-93/vite-electron-builder#664]
1. npm install file-type
2. add to main/src/index.ts
```
import * as fileType from 'file-type';

console.log(fileType);
```

<img width="647" alt="Снимок экрана 2022-01-09 в 17 48 46" src="https://user-images.githubusercontent.com/4738878/148670922-cf6c74b4-3b4f-45b5-bb38-fca3995b5e7d.png">

**Comment by cawa-93** [comment]
Try add `node:buffer` to `externals`

**Comment by cawa-93** [comment]
Or, better, try set `build.ssr: true`

**Comment by vinchilive** [comment]
@cawa-93 
1. if I set `ssr: true,` and call file-type
```
import {fileTypeFromBuffer} from 'file-type';

console.log(fileTypeFromBuffer);
```
I get this error
```
[main] App threw an error during load
19:51:05 [main] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/node_modules/file-type/index.js from /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/packages/main/dist/index.cjs not supported.
Instead change the require of index.js in /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/packages/main/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
```
2. if I add `'node:buffer',` to `external` it seems to do the trick, but if I edit the code sometimes the app is crashing on save
```
19:54:40 [main] [32568:0110/195440.662687:ERROR:process_singleton_posix.cc(1201)] Failed to extract pid from path: /Users/vinchilive/Library/Application Support/vite-electron-builder/SingletonLock
```

**Comment by vinchilive** [comment]
actually the second case is happening on the clean repo as well

**Comment by vinchilive** [comment]
looks like the issue is in the dynamic import of electron-devtools-installer
```
.then(() => import('electron-devtools-installer'))
.then(({default: installExtension, VUEJS3_DEVTOOLS}) => 
```
if I do it statically the error is gone
```
import installExtension, { VUEJS3_DEVTOOLS } from 'electron-devtools-installer'

if (import.meta.env.DEV) {
  app.whenReady()
    .then(() => {
      installExtension(VUEJS3_DEVTOOLS, {
        loadExtensionOptions: {
          allowFileAccess: true,
        },
      })
    })
    .catch(e => console.error('Failed install extension:', e));
}
```
and imports are working fine with other packages, this one do not crash the app:
```
import('file-type').then(({fileTypeFromBuffer}) => {
  console.log(fileTypeFromBuffer)
})
```

**Comment by cawa-93** [comment]
@vinchilive 

> 1. if I set `ssr: true,` and call file-type
> 
> 
> ```
> import {fileTypeFromBuffer} from 'file-type';
> 
> console.log(fileTypeFromBuffer);
> ```
> 
> I get this error
> 
> ```
> [main] App threw an error during load
> 19:51:05 [main] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/node_modules/file-type/index.js from /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/packages/main/dist/index.cjs not supported.
> ```

It seems to upstream issue.

At the moment, the ESM is not supported in the electron. So `main` package completly transpile to commonjs. And in runtime you got:

```js
f = require('file-type');
```

But, As far as I can see, the `file-type` does not provide the module in cjs, but only in esm.

**Comment by cawa-93** [comment]
> @cawa-93
> 
>     1. if I set `ssr: true,` and call file-type
> 
> 
> ```
> import {fileTypeFromBuffer} from 'file-type';
> 
> console.log(fileTypeFromBuffer);
> ```
> 
> I get this error
> 
> ```
> [main] App threw an error during load
> 19:51:05 [main] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/node_modules/file-type/index.js from /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/packages/main/dist/index.cjs not supported.
> Instead change the require of index.js in /Users/vinchilive/Documents/dev/firestarter/vite-electron-builder/packages/main/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
> ```
> 
>     2. if I add `'node:buffer',` to `external` it seems to do the trick, but if I edit the code sometimes the app is crashing on save
> 
> 
> ```
> 19:54:40 [main] [32568:0110/195440.662687:ERROR:process_singleton_posix.cc(1201)] Failed to extract pid from path: /Users/vinchilive/Library/Application Support/vite-electron-builder/SingletonLock
> ```
> 
> ```
> node -v
> v17.2.0
> ```

It's like a separate sciatica. However, I cannot reject it. Did you specify that this is specific to m1? https://github.com/cawa-93/vite-electron-builder/issues/554 may be relevant. In any case, this deserves a separate issue.

**Comment by vinchilive** [comment]
```
ssr: {
    noExternal: ['file-type'],
  },
  ```
that one helped, thanks 👍 
as for the issue with the app crashing I tested and reproduced it on 2 M1 macs and tested and cannot reproduce it on intel mac. I agree that it is a separate issue so we can close this one
