### ISSUE TITLE
After building the project it gives error net::ERR_FILE_NOT_FOUND in the console

### ISSUE THREAD

**Issue by jayprakashdev** [cawa-93/vite-electron-builder#671]
**Describe the bug**
I tried to build my app with the command "npm run compile" and then i installed the app using the the installed generated through the build. It opened with a white blank screen with a console log net::ERR_FILE_NOT_FOUND.

I'm on mac os monterey 

**To Reproduce**
Steps to reproduce the behaviour:
1. Compile the. app
2. Install it through the installer
3.  Check console

**Expected behaviour**
The app should open as it was in the development

**Screenshots**
<img width="852" alt="Screenshot 2022-01-12 at 10 33 35 AM" src="https://user-images.githubusercontent.com/86955868/149066990-7632cdbd-04ee-43cb-bd31-ddf2faea7ba5.png">

**Comment by cawa-93** [comment]
Please, provide minimal reproduction repo. What is your environment?
