### ISSUE TITLE
Error: The following dependencies are imported but could not be resolved: index.1828923a.js

### ISSUE THREAD

**Issue by Minori-ty** [cawa-93/vite-electron-builder#678]
**Describe the bug**
every time, after I npm run build, it will generate a bundle js script in the renderer/dist/index.html. And when I add a new dependencies or delete a dependencies and use script npm run watch, it will show that, and I hava to manually delete the bundle script.

![image](https://user-images.githubusercontent.com/79521943/149434069-dfd8bc46-b13d-4060-81d4-5a26ffdde39f.png)

**To Reproduce**
1.npm install a dependencies 
2.npm run build
3.npm uninstall the dependencies 
4.npm run watch

**Expected behavior**
I expect it can be resolved, and I don't need to manually delete the bundle script in renderer/dist/index.html.

**Screenshots**

**Additional context**

**Comment by boparaiamritcsb** [comment]
@Minori-ty Run following Command

```
// clean dist repo and node_modules and anything which is ignored in .gitignore
git clean -xdf 
npm install
npm run watch
```

**Comment by cawa-93** [comment]
Convenient. I faced this. But I was unable to determine the source of the problem.

If I'm not mistaken, removing the `packages/renderer/dist` should solve this problem once.

I will try to resolve this issue when I have time.
