### ISSUE TITLE
Please Add Support for Tailwind CSS

### ISSUE THREAD

**Issue by boparaiamritcsb** [cawa-93/vite-electron-builder#679]
**Is your feature request related to a problem? Please describe.**
Please Add Support for Tailwind CSS [https://tailwindcss.com/](url)

**Comment by cawa-93** [comment]
No. I try to keep a minimum of functions in this template. And to introduce something that is likely to benefit everyone without exception.

Tailwind is a niche thing. And it is very easy to integrate yourself.

**Comment by boparaiamritcsb** [comment]
Yeah, I try it, But there is a challenge in the watch, it's working in compile mode but there is a problem in watch mode and not being able to use a template. Already spent 3-4 hrs, but was not able to get it.

**Comment by boparaiamritcsb** [comment]
Thanks 👍

**Comment by SimonBerens** [comment]
@boparaiamritcsb how did you get it working in compile mode? for me, if I add
```
  content: ['./packages/renderer/src/**/*.{vue,js,ts,jsx,tsx}'],
```
to the `tailwind.config.js` it works in watch mode, but when I compile/release it the css is not included (I assume because of something to do with electron builder?)

**Comment by SimonBerens** [comment]
changing it to 
```
content: ['./**/*.{vue,js,ts,jsx,tsx}']
```
worked, but now the styles are out of wack

**Comment by coderminer** [comment]
in the package.json change 
`"build:renderer": "cd ./packages/renderer vite build "`
to
`"build:renderer": "vite build --config ./packages/renderer/vite.config.js"`

worked for me

**Comment by cameronkloot** [comment]
I haven't been able to get tailwind configured correctly. Would anyone be able to share a repo created from this template which implements tailwinds?

**Comment by SimonBerens** [comment]
@cameronkloot I got it working here https://github.com/SimonBerens/sleep

**Comment by cameronkloot** [comment]
> @cameronkloot I got it working here https://github.com/SimonBerens/sleep

I neglected to import the css file.... That'd do it. Thank you

**Comment by HarveyKandola** [comment]
> vite build --config ./packages/renderer/vite.config.js

Fixed for me as well -- thank you for documenting this @coderminer !

You able to explain why this change is required to get PostCSS to process Tailwind CSS files?
