### ISSUE TITLE
I can't reference any 3rd Part Node.js modules in preload pkg.

### ISSUE THREAD

**Issue by dohooo** [cawa-93/vite-electron-builder#715]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/32405058/150641563-a316ff9b-1c59-441f-8be3-412e931fcc0e.png">

Like this, I declare such a global method in preload pkg, but it gives me this error.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/32405058/150641603-078555f7-37bf-4633-8dd2-3ede4ebad88e.png">

It is the first time for me to use electron with Vitejs. I had read many docs and consulted many materials, but I still can't solve this problem. So is this problem related to this template? Or some other common problem? Ask for help 🙏 @cawa-93

**Comment by cawa-93** [comment]
First things first read https://github.com/cawa-93/vite-electron-builder#working-with-dependencies. If you did everything according to the documentation, share your demo and I will try to check it ASAP.

**Comment by dohooo** [comment]
@cawa-93  

```shell
git clone https://github.com/dohooo/vite-electron-builder-reproduce.git
cd vite-electron-builder-reproduce
yarn
yarn watch
```

Then you will see this error. But I'm not sure it's just the MAC M1
<img width="650" alt="image" src="https://user-images.githubusercontent.com/32405058/150663088-c0c997ff-6e25-40d7-8372-12d5f461ba03.png">

**Comment by dohooo** [comment]
> But it doesn't always work. Vite was designed to work with browser-oriented packages. So it is not able to bundle Node built-in modules, or native dependencies, or some Node.js specific packages, or Electron itself.
Modules that Vite is unable to bundle are forced to be supplied as external in vite.config.js. External modules are not optimized and their imports remain during runtime.

THX! I fixed it!

**Comment by dohooo** [comment]
> First things first read https://github.com/cawa-93/vite-electron-builder#working-with-dependencies. If you did everything according to the documentation, share your demo and I will try to check it ASAP.

Sorry, I was so careless

**Comment by dohooo** [comment]
Sorry, I found that the module can be introduced normally, but there is still a problem with hot update, so I tried to start from scratch with your template, and found that there is still a problem.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/32405058/150668214-1fde6cbf-0837-4414-b28b-7f1e004ed820.png">

Reproduce steps:
1. git clone [THIS_TEMPLATE]
2. yarn add usb ( I didn't try any of the other modules, although I felt the problems were roughly the same )
3. yarn watch ( The error will come out (may need to be MAC M1 as well) )

I did the following configuration:
> packages/preload/vite.config.js
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/32405058/150668302-1002800b-8f41-435b-bacd-4bb5b4fe45b8.png">

But it still tells me the error above, And the Sourcemap browser tries to find a strange location.
I've been trying to solve this problem for a long time, but I still can't 🙏 @cawa-93

**Comment by cawa-93** [comment]
I was unable to reproduce your problem on Windows.

```ts
// preload/src/index,ts
import {usb} from 'usb'; // Note named import

contextBridge.exposeInMainWorld('getDeviceList', () => usb.getDeviceList());
```
```diff
// preload/vite.config.js
    rollupOptions: {
      external: [
+       'usb',
        'electron',
        ...builtinModules.flatMap(p => [p, `node:${p}`]),
      ],
      output: {
        entryFileNames: '[name].cjs',
      },
    },
```
![зображення](https://user-images.githubusercontent.com/1662812/150670903-fc591b48-72f5-42cd-9475-dbc1d343a322.png)

**Comment by dohooo** [comment]
> I was unable to reproduce your problem on Windows.
> 
> ```ts
> // preload/src/index,ts
> import {usb} from 'usb'; // Note named import
> 
> contextBridge.exposeInMainWorld('getDeviceList', () => usb.getDeviceList());
> ```
> 
>  ```diff
> // preload/vite.config.js
>     rollupOptions: {
>       external: [
> +       'usb',
>         'electron',
>         ...builtinModules.flatMap(p => [p, `node:${p}`]),
>       ],
>       output: {
>         entryFileNames: '[name].cjs',
>       },
>     },
> ```
> 
> ![зображення](https://user-images.githubusercontent.com/1662812/150670903-fc591b48-72f5-42cd-9475-dbc1d343a322.png)

Let me try it

**Comment by dohooo** [comment]
After making the same changes as you did, the problem remains

**Comment by dohooo** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/32405058/150671057-9c35cd1f-93ed-4c40-8956-165cd7f2de68.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/32405058/150671054-6a0f9fa9-3a7c-4a8f-8543-7340c18ef8b4.png">

When I remove it, everything goes back to normal

**Comment by cawa-93** [comment]
What is your output? I got
```js
var usb = require("usb");
electron.contextBridge.exposeInMainWorld("getDeviceList", () => usb.usb.getDeviceList());
```
If you have the same, then the problem is somewhere else. Maybe the `usb` package does not have native module for macos m1 or something

**Comment by dohooo** [comment]
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/32405058/150675679-77f69d67-4df6-48cf-9d59-d18b72e5f8e7.png">

I got the same, Do you have any other suggestions

**Comment by dohooo** [comment]
However, I can execute the USB package on my M1 directly through the `node` command，why

**Comment by dohooo** [comment]
I found this https://github.com/node-usb/node-usb-example-electron/issues/1

**Comment by cawa-93** [comment]
Is't work if you downgrade electron version <15.0?

**Comment by dohooo** [comment]
I downgrade electron version from 16.x to 14.x it works. I decided to leave it at that, thank you for your help and thanks again to this great lib.

By the way, the preload part written nodejs logic, and then through the packages/preload/index. The ts export is standard practice for?

**Comment by dohooo** [comment]
It's exactly what he said https://github.com/node-usb/node-usb-example-electron/issues/1#issuecomment-1013063461

**Comment by dohooo** [comment]
By the way, for the current default 16.0.7 electron version, M1 cannot be downloaded to the corresponding module, I don't know why, but it will prompt 404.

M1 is fast, but everything else is trouble

**Comment by dohooo** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/32405058/150676578-4976724f-c0f9-457d-9a57-1e38785eaf4e.png">

Maybe you can add a reminder for M1 users in readme. I have encountered a lot of trouble from MBP M1 in the last two days

**Comment by dohooo** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/32405058/150676753-ef9f62ce-44d6-4a8c-92dc-939f92d4283d.png">

It's working fine now, but do you know what this Sourcemap warning is about?

**Comment by cawa-93** [comment]
> Maybe you can add a reminder for M1 users in readme. I have encountered a lot of trouble from MBP M1 in the last two days

No. It's not template-specific issue but platform-specific. I would like to keep the documentation minimal and focused on things that are specific to the template. In addition, I do not have mac, so I will not be able to track the urgency of this problem. You should ping upstream developers for m1 support
