### ISSUE TITLE
Browser always crashed when modified preload package code.

### ISSUE THREAD

**Issue by dohooo** [cawa-93/vite-electron-builder#730]
**Describe the bug**
Browser always crashed when modified preload package code.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/32405058/151541218-53cbb8bb-fb2b-46cb-bce4-d925975def7e.png">

https://user-images.githubusercontent.com/32405058/151542057-f5ebb6ee-1dc1-4aff-ae6f-e439d72dbfed.mov

These are the only things I've changed
1. add packages `"usb": "^2.0.3"` and add external to preload vide.config
2. modified electron versions to `"electron": "14.2.3"` because [this](https://github.com/node-usb/node-usb-example-electron/issues/1#issuecomment-1013063461)
3. import USB modules to ./packages/preload/src/sha256sum.ts file

🙏 I know maybe this is not the problem of your warehouse, but I really have no idea. If possible, I hope to sponsor your time.
Save me，Save me，Save me

**To Reproduce**
1. git clone https://github.com/dohooo/vite-electron-builder-reproduction.git
2. yarn
3. yarn watch
4. modify ./packages/preload/src/sha256sum.ts file
```ts
console.log(getDeviceList(), '1');
// to
console.log(getDeviceList(), '2');
```
Repeat several times the browser will be crash.

**Expected behavior**
Normal hot update

**Comment by dohooo** [comment]
Please @cawa-93

**Comment by cawa-93** [comment]
Does problem exist if you remove `usb` package?

**Comment by dohooo** [comment]
> Does problem exist if you remove `usb` package? 

yes🤯

**Comment by cawa-93** [comment]
I Reproduce bug in clear Electron fiddle and seems `usb` package crash webview.
Try it: https://gist.github.com/f564ef9f0f7089658019615cd3ecc558

**Comment by cawa-93** [comment]
Probably you should create issue in electron repo

**Comment by dohooo** [comment]
> I Reproduce bug in clear Electron fiddle and seems `usb` package crash webview.
> Try it: https://gist.github.com/f564ef9f0f7089658019615cd3ecc558

It seems so. I'm very sorry and thank you
