### ISSUE TITLE
A script to preview only the renderer part in the browser

### ISSUE THREAD

**Issue by massifrg** [cawa-93/vite-electron-builder#740]
I'd need a script in package.json to preview only the renderer part in the browser.
I'd like my app to work both on a server and inside a standalone, desktop, electron-based app.
The script I'm asking for would preview only the server-based version.
I tried this:
```
  // "scripts" section of package.json
  "dev": "vite",
```
but it does not work.
(BTW thanks for this project, it solved me the problems I had with electron's preload)

**Comment by cawa-93** [comment]
Look at the `build:rebderer`. It's what you want but in dev mode

**Comment by massifrg** [comment]
Thank you! I got it:
```
    "build:renderer": "cd ./packages/renderer && vite build",
    ...
    "dev": "cd ./packages/renderer && vite",
```
or it may be:
```
    "watch:renderer": "cd ./packages/renderer && vite",
```
