### ISSUE TITLE
No main window opened on MacOS 

### ISSUE THREAD

**Issue by sagacity** [cawa-93/vite-electron-builder#750]
**Describe the bug**
After doing a clean checkout and install, `npm run watch` starts the Electron app, but no main window appears. The menu is visible, but no window is present.

This is on MacOS Monterey 12.2.

**To Reproduce**
1. Go to the main repo and clone it
2. `npm install` 
3. `npm run watch`
4. No window pops up

**Additional context**
I thought it might be an issue with Electron 17, but reverting to an older commit (7d11dea480400e14d1b4b7f910ea8ab8f472b00d, just before the upgrade to Electron 17) has the same issue.

Running with `ELECTRON_ENABLE_LOGGING=1` does not show any errors.

I do notice that there is no `dist` folder appearing in `packages/renderer` but that may be by design?

The example cloned from https://github.com/electron/electron-quick-start works fine, so it's not a problem in Electron 17 itself, I guess.

**Comment by cawa-93** [comment]
I just tried it on Windows and see no problem. Maybe someone else on MakOS will be able to check and report it.

**Comment by sagacity** [comment]
I did a bit more debugging:
* An empty window does show up if I set `show: true` in the `new BrowserWindow` options in `mainWindow.ts`, but it doesn't get filled with anything
* Loading the renderer URL doesn't return (i.e. `await browserWindow.loadURL(pageUrl)` hangs)
* I guess because of this the `ready-to-show` event never gets fired and the window doesn't open.

I have no idea why `loadURL` would hang, though.

Interestingly, running e2e tests works fine, and I see the Vite example pop up briefly (as you'd expect).

**Comment by sagacity** [comment]
Changing the listening port (which defaults to `3000`) to something else seems to do the trick!

```
const sharedConfig = {
  server: {
    port: 5757,
  },
  ...
}
```

Port 3000 was apparently being blocked by a suspended Docker container. I guess Docker for Mac didn't clean it up correctly.

Anyway, mystery solved! Nothing to fix on your end :)

**Comment by cawa-93** [comment]
This can be a problem upstream. Vite is not tied tightly to the port. It checks the availability of 3000, but if this port is blocked then it should use 3001, 3002 and so on.

The watch script must respect this behavior. It waits for Vite to run on some port and then passes this information to the main script.

https://github.com/cawa-93/vite-electron-builder/blob/57d932b8fce7bd8cb07a53aa10e8f4429ac26ce6/scripts/watch.js#L53-L57

So, if port 3000 is busy, it should start at 3001 and the main window should load http://localhost:3001. Looks like something went wrong in your case:
Perhaps Vite could not determine that port 3000 was blocked.
Or it's a template bug.

**Comment by sagacity** [comment]
Yes, exactly. I'll try to see if I can reproduce and then report to Vite upstream.
