### ISSUE TITLE
Remove dts-cb/build:preload:types

### ISSUE THREAD

**Issue by JoCat** [cawa-93/vite-electron-builder#756]
It seems to me that using dts-cb imposes an extra cost, in terms of requiring a restart every time the code changes.

There is an easier way to pass types in the renderer process.
For example:

You declare all the exported functionality in one place:
https://github.com/AuroraTeam/Launcher/blob/b223607835deab305ce71c5c7008449c8cec99aa/src/preload/index.ts

and import ad types into the file:
https://github.com/AuroraTeam/Launcher/blob/b223607835deab305ce71c5c7008449c8cec99aa/src/renderer/renderer.d.ts

this solution allows you to keep the code clean, you can clearly define what you need to export in one place, while you do not need to run the `build:preload:types` task every time you add new functionality to the export.

**Comment by cawa-93** [comment]
How should this work in case if not one point but many are exposed? When does each module have its own exposed api?

**Comment by JoCat** [comment]
> How should this work in case if not one point but many are exposed? When does each module have its own exposed api?

no way, in this case, you can import additional types

**Comment by cawa-93** [comment]
I agree. I don't like how it works now. You need to think about the best approach to transfer preload contracts to the renderer. However, I don't like the idea of describing all the apps in one place.

I want the preload to be flexible. That in it there could be both one and several modules. And each module could expose one or more APIs.

🤔🤔🤔🤔🤔

**Comment by JoCat** [comment]
For example:

```ts
// preload.ts
export const ipc = {
  on: ipcRenderer.on,
  send: ipcRenderer.send,
  invoke: ipcRenderer.invoke,
};

contextBridge.exposeInMainWorld("ipc", ipc);
```

```ts
// another-preload.ts
export const logger = {
  info: logger.info,
  warn: logger.warn,
  error: logger.error,
};

contextBridge.exposeInMainWorld("logger", logger);
```

```ts
// renderer.d.ts
declare type IPC = typeof import("../preload/preload").ipc;
declare type Logger = typeof import("../preload/another-preload").logger;

declare interface Window {
  ipc: IPC;
  logger: Logger;
}

declare const ipc: IPC
declare const logger: Logger;

// or (global only)

declare const { ipc }: typeof import("../preload/preload");
declare const { logger }: typeof import("../preload/another-preload");
```
