### ISSUE TITLE
How to use electron-store.

### ISSUE THREAD

**Issue by mrandpz** [cawa-93/vite-electron-builder#76]
I tried to use https://github.com/sindresorhus/electron-store, but it reported an error.

preload/index.ts
```js
import * as Store from 'electron-store';
const api = {
  getStore: () => new Store(),
}
```

some.vue
```
import { useElectron } from '@/use/electron';
const { getAppPath,getstore} = useElectron();

 console.log(getstore()); // Then report an error
```

**Comment by mrandpz** [comment]
emmm.I found the following solution

```js
rollupOptions: {
      external: require('./external-packages').default,
      plugins: [
        {
          name: '@rollup/plugin-cjs2esm',
          transform(code, filename) {
            if (filename.includes('/node_modules/')) {
              return code;
            }

            const cjsRegexp = /(const|let|var)[\n\s]+(\w+)[\n\s]*=[\n\s]*require\(["|'](.+)["|']\)/g;
            const res = code.match(cjsRegexp);
            if (res) {
              // const Store = require('electron-store') -> import Store from 'electron-store'
              code = code.replace(cjsRegexp, `import $2 from '$3'`);
            }
            return code;
          },
        },
      ],
    },
```

```
/*@replace = import Store from 'electron-store'*/ const Store = require('electron-store');

export default new Store();

```

**Comment by cawa-93** [comment]
Please indicate at what stage you receive the error and what the error is

**Comment by cawa-93** [comment]
From the settings that are specific to this template, you need to add this library to `external` array:
```diff
// config/external-packages.js
module.exports.external = [
   'electron',
   'electron-updater',
+  'electron-store',
];
```
Next, you need to refer to the electron-store documentation to learn how to use this library in a modern electron environment. For example, you may need an [`initRenderer()`](https://github.com/sindresorhus/electron-store#initrenderer) call. Also, you will have to set the following parameters for the production environment as well:

```diff
webPreferences: {
  preload: join(__dirname, '../preload/index.cjs.js'),
        
-  contextIsolation: env.MODE !== 'test',   // Spectron tests can't work with contextIsolation: true
+  contextIsolation: false,

-  enableRemoteModule: env.MODE === 'test', // Spectron tests can't work with enableRemoteModule: false
+  enableRemoteModule: true,
}
```

**Comment by s00d** [comment]
> From the settings that are specific to this template, you need to add this library to `external` array:
> 
> ```diff
> // config/external-packages.js
> module.exports.external = [
>    'electron',
>    'electron-updater',
> +  'electron-store',
> ];
> ```
> 
> Next, you need to refer to the electron-store documentation to learn how to use this library in a modern electron environment. For example, you may need an [`initRenderer()`](https://github.com/sindresorhus/electron-store#initrenderer) call. Also, you will have to set the following parameters for the production environment as well:
> 
> ```diff
> webPreferences: {
>   preload: join(__dirname, '../preload/index.cjs.js'),
>         
> -  contextIsolation: env.MODE !== 'test',   // Spectron tests can't work with contextIsolation: true
> +  contextIsolation: false,
> 
> -  enableRemoteModule: env.MODE === 'test', // Spectron tests can't work with enableRemoteModule: false
> +  enableRemoteModule: true,
> }
> ```

it's bad idea. need use preload

```ts
// packages/preload/src/index.ts
const api: ElectronApi = {
  versions: process.versions,
  configStore: {
    get: (key: string, def?: any) => configStore.get(key, def),
    set: (key: string, val?: any) => configStore.set(key, val),
    clear: () => configStore.clear(),
    delete: (key: string) => configStore.delete(key),
    has: (key: string) => configStore.has(key),
  },
}

//packages/preload/types/electron-api.d.ts
interface ElectronApi {
  readonly versions: Readonly<NodeJS.ProcessVersions>
  readonly configStore: {
    get: (key: string, def?: any) => any,
    set: (key: string, val?: any) => any,
    clear: () => void,
    delete: (key: string) => void,
    has: (key: string) => boolean,
  }
```

```ts
//renderer
import {useElectron} from '/@/use/electron'
const {configStore} = useElectron()
//...
configStore.get(key)
```

**Comment by jotyy** [comment]
> > From the settings that are specific to this template, you need to add this library to `external` array:
> > ```diff
> > // config/external-packages.js
> > module.exports.external = [
> >    'electron',
> >    'electron-updater',
> > +  'electron-store',
> > ];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Next, you need to refer to the electron-store documentation to learn how to use this library in a modern electron environment. For example, you may need an [`initRenderer()`](https://github.com/sindresorhus/electron-store#initrenderer) call. Also, you will have to set the following parameters for the production environment as well:
> > ```diff
> > webPreferences: {
> >   preload: join(__dirname, '../preload/index.cjs.js'),
> >         
> > -  contextIsolation: env.MODE !== 'test',   // Spectron tests can't work with contextIsolation: true
> > +  contextIsolation: false,
> > 
> > -  enableRemoteModule: env.MODE === 'test', // Spectron tests can't work with enableRemoteModule: false
> > +  enableRemoteModule: true,
> > }
> > ```
> 
> it's bad idea. need use preload
> 
> ```ts
> // packages/preload/src/index.ts
> const ConfigStore = require('electron-store')
> const configStore = new ConfigStore()
> 
> const api: ElectronApi = {
>   versions: process.versions,
>   configStore: {
>     get: (key: string, def?: any) => configStore.get(key, def),
>     set: (key: string, val?: any) => configStore.set(key, val),
>     clear: () => configStore.clear(),
>     delete: (key: string) => configStore.delete(key),
>     has: (key: string) => configStore.has(key),
>   },
> }
> ```
> 
> ```ts
> //packages/preload/types/electron-api.d.ts
> interface ElectronApi {
>   readonly versions: Readonly<NodeJS.ProcessVersions>
>   readonly configStore: {
>     get: (key: string, def?: any) => any,
>     set: (key: string, val?: any) => any,
>     clear: () => void,
>     delete: (key: string) => void,
>     has: (key: string) => boolean,
>   }
> ```
> 
> ```ts
> //renderer
> import {useElectron} from '/@/use/electron'
> const {configStore} = useElectron()
> //...
> configStore.get(key)
> ```

I followed your configuration using preload, but got an error that reload(ctrl+R) is disabled. Do you have any suggestions?
