### ISSUE TITLE
This crashs everytime when we import ipfs package from vue code

### ISSUE THREAD

**Issue by yingshaoxo** [cawa-93/vite-electron-builder#780]
I'm using this package: `yarn add ipfs-http-client`

And if I import it from vue3, then I run `yarn watch`, I got errors

https://github.com/ipfs/js-ipfs/issues/3858#issuecomment-1046617510

___

```bash
yarn run v1.22.17
$ node scripts/watch.js
Pre-bundling dependencies:
  vue
  element-plus
  ipfs-http-client
(this will be run only when your dependencies or config have changed)
✘ [ERROR] No matching export in "browser-external:url" for import "parse"

    node_modules/electron-fetch/lib/index.es.js:1:9:
      1 │ import { parse, format, resolve } from 'url';
        ╵          ~~~~~

✘ [ERROR] No matching export in "browser-external:url" for import "format"

    node_modules/electron-fetch/lib/index.es.js:1:16:
      1 │ import { parse, format, resolve } from 'url';
        ╵                 ~~~~~~

✘ [ERROR] No matching export in "browser-external:url" for import "resolve"

    node_modules/electron-fetch/lib/index.es.js:1:24:
      1 │ import { parse, format, resolve } from 'url';
        ╵                         ~~~~~~~

✘ [ERROR] No matching export in "browser-external:http" for import "STATUS_CODES"

    node_modules/electron-fetch/lib/index.es.js:3:9:
      3 │ import { STATUS_CODES } from 'http';
        ╵          ~~~~~~~~~~~~

✘ [ERROR] No matching export in "browser-external:stream" for import "PassThrough"

    node_modules/electron-fetch/lib/index.es.js:6:17:
      6 │ import Stream, { PassThrough } from 'stream';
        ╵                  ~~~~~~~~~~~

Error: Build failed with 5 errors:
node_modules/electron-fetch/lib/index.es.js:1:9: ERROR: No matching export in "browser-external:url" for import "parse"
node_modules/electron-fetch/lib/index.es.js:1:16: ERROR: No matching export in "browser-external:url" for import "format"
node_modules/electron-fetch/lib/index.es.js:1:24: ERROR: No matching export in "browser-external:url" for import "resolve"
node_modules/electron-fetch/lib/index.es.js:3:9: ERROR: No matching export in "browser-external:http" for import "STATUS_CODES"
node_modules/electron-fetch/lib/index.es.js:6:17: ERROR: No matching export in "browser-external:stream" for import "PassThrough"
    at failureErrorWithLog (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1602:15)
    at /Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1248:28
    at runOnEndCallbacks (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1033:63)
    at buildResponseToResult (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1246:7)
    at /Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:1355:14
    at /Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:665:9
    at handleIncomingPacket (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/yingshaoxo/CS/libgen2/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:url" for import "parse"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:url" for import "format"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:url" for import "resolve"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:http" for import "STATUS_CODES"'
    },
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'No matching export in "browser-external:stream" for import "PassThrough"'
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cawa-93** [comment]
You tried import build-in node.js modules in renderer, but it's impossible. Read [Working with dependencies](https://github.com/cawa-93/vite-electron-builder#working-with-dependencies) section.

**Comment by yingshaoxo** [comment]
> You tried import build-in node.js modules in renderer, but it's impossible. Read [Working with dependencies](https://github.com/cawa-93/vite-electron-builder#working-with-dependencies) section.

Hi, I would love to have a solution

Because, as you see, `ipfs-http-client` is indeed a browser-based package, it's not a node package: https://github.com/ipfs-examples/js-ipfs-http-client-bundle-webpack/blob/main/src/App.js#L2

I just don't get why by only importing it, I got errors.

**Comment by cawa-93** [comment]
Something in your dependency chain imports the `browser-external:http`, which in turn tries to import the `http`, which leads to an error. You should set `ipfs-http-client` as an external dependency, import it into the preload, and expose the method to renderer.

**Comment by yingshaoxo** [comment]
> Something in your dependency chain imports the `browser-external:http`, which in turn tries to import the `http`, which leads to an error. You should set `ipfs-http-client` as an external dependency, import it into the preload, and expose the method to renderer.

Thanks, I tried that method.

It indeed works. 

But I lost the type-definition, which makes me annoying, which may let me have a chance to make mistakes.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/17190829/154926959-bf3b2095-4ff5-43f1-9732-3ab9f13a25c3.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/17190829/154926994-ba37fd51-fa8d-481a-b047-d62eb0e46873.png">

**Comment by yingshaoxo** [comment]
> > Something in your dependency chain imports the `browser-external:http`, which in turn tries to import the `http`, which leads to an error. You should set `ipfs-http-client` as an external dependency, import it into the preload, and expose the method to renderer.
> 
> Thanks, I tried that method.
> 
> It indeed works.
> 
> But I lost the type-definition, which makes me annoying, which may let me have a chance to make mistakes.
> 
> <img alt="image" width="463" src="https://user-images.githubusercontent.com/17190829/154926959-bf3b2095-4ff5-43f1-9732-3ab9f13a25c3.png">
> 
> <img alt="image" width="346" src="https://user-images.githubusercontent.com/17190829/154926994-ba37fd51-fa8d-481a-b047-d62eb0e46873.png">

Alright, I've fixed it:

<img width="230" alt="image" src="https://user-images.githubusercontent.com/17190829/154932031-1732848d-1c42-4398-a18b-46edd6584d9e.png">

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/17190829/154932247-545cc7ae-4ce6-477f-aaf0-e1f069d21fb8.png">

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/17190829/154932359-07e0756c-cad5-44f1-8e84-0c2ab8b518fb.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/17190829/154932320-3b8e26db-9a97-4f32-9bbd-937e30f4d39e.png">

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/17190829/154932432-bf60daba-ae11-4566-a9c3-d7a3a6585a80.png">

<img width="448" alt="image" src="https://user-images.githubusercontent.com/17190829/154932610-0a75f667-7c77-42d9-91ba-ba66e12439b0.png">
