### ISSUE TITLE
Electron sandbox_bundle.js script failed to run

### ISSUE THREAD

**Issue by raphael10-collab** [cawa-93/vite-electron-builder#798]
I followed all  the steps suggested here: https://github.com/cawa-93/vite-electron-builder/discussions/770 to use `React.js` instead of `Vue.js`. 

The app shows up, but  some strange error messages appear :  

    (base) raphy@pc:~/ViteElectronReactBuilder$ yarn run watch
    yarn run v1.22.18
    $ node scripts/watch.js
    vite v3.0.0-alpha.11 building SSR bundle for development...
    
    watching for file changes...
    
    build started...
    ✓ 3 modules transformed.
    rendering chunks (1)...Sourcemap is likely to be incorrect: a plugin (unplugin-auto-expose-preload) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
    dist/index.cjs   0.55 KiB
    dist/index.cjs.map 0.10 KiB
    built in 50ms.
    vite v3.0.0-alpha.11 building SSR bundle for development...
    
    watching for file changes...
    
    build started...
    ✓ 3 modules transformed.
    dist/index.cjs   4.00 KiB
    dist/index.cjs.map 10.38 KiB
    built in 67ms.
    8:47:14 PM [vite] ✨ new dependencies optimized: react, react-dom/client
    8:47:15 PM [vite] ✨ optimized dependencies changed. reloading
    8:47:15 PM [main] Failed create window: Error: ERR_ABORTED (-3) loading 'http://localhost:5173/'
        at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
        at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)
        at EventEmitter.emit (node:events:526:28) {
      errno: -3,
      code: 'ERR_ABORTED',
      url: 'http://localhost:5173/'
    }
    8:47:15 PM [main] [84984:0615/204715.636173:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
    [84984:0615/204715.636210:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)

![image](https://user-images.githubusercontent.com/70313067/173902444-4aa3a03d-831e-4b40-9303-46e986663a4e.png) 
![image](https://user-images.githubusercontent.com/70313067/173904009-d01ee0cc-f19b-4843-b92f-75ba2f6e7b4f.png)

You can find the repo here:  https://github.com/raphael10-collab/ViteElectronReactBuilder

**Comment by cawa-93** [comment]
I don't see any errors with the last committee in this template. You should probably contact the author of the react fork
