### ISSUE TITLE
Watch/hot-reload support for multiple renderers

### ISSUE THREAD

**Issue by jakeyizle** [cawa-93/vite-electron-builder#800]
**Is your feature request related to a problem? Please describe.**
I am unsure how to implement multiple Renderer windows using the Vite server. 
The main window is created (in dev) with: `import.meta.env.VITE_DEV_SERVER_URL`
But the only way I have found to create a second renderer is to build and then 
`  const pageUrl = new URL('../secondRenderer/dist/index.html', 'file://' + __dirname).toString();`
Which works, but loses out on all of the plus sides of using the server (debug, hot reload, etc)

Is there a way to configure Vite to support additional renderers? I can only find information on additional paths for multi-page sites but my use case has an actual 2nd window for a user to interact with.

**Comment by cawa-93** [comment]
So, why you can't use two pages for each window?
