### ISSUE TITLE
Better logging for the main process

### ISSUE THREAD

**Issue by v-dawg** [cawa-93/vite-electron-builder#807]
**Is your feature request related to a problem? Please describe.**
The logs of the main process do not display information like filepath and linenumber.
This makes debugging hard or you end up writing wordy `console.log`s which give you more information.

**Describe the solution you'd like**
I just found [`Ololog!`](https://github.com/xpl/ololog) and I am amazed by how nice it is. It fits this use-case perfectly. It even uses the source-maps **without configuration**! (I am not affiliated with it)
So adding it to the dependencies and writing one/two lines about it in the docs would help a lot of the users of this template :)

**Describe alternatives you've considered**
I found [this](https://stackoverflow.com/a/60305881/9578667) snippet on Stackoverflow, which is really nice- but it cannot compare to the beautiful and simple logging of `Ololog!`.

**Additional context**
No more!
<img width="847" alt="image" src="https://user-images.githubusercontent.com/28539403/178115230-664405ef-bf2d-42a2-8245-1f423913574d.png">

**Comment by cawa-93** [comment]
Hello. Thanks for the offer, but I will decline it. It can be a good tool, but is it necessary? Will everyone need it? I try to keep this starter _template_ as minimal and versatile as possible so that everyone can add whatever tools they want.
