### ISSUE TITLE
add launch script for vscode

### ISSUE THREAD

**Issue by stalkercn** [cawa-93/vite-electron-builder#859]
[**Is your feature request related to a problem? Please describe.**
with recommended vscode launch script from electron official docs, breakpoints in the main script is not working.

**Describe the solution you'd like**
add a working, debuggable launch script for vscode.

**Describe alternatives you've considered**
add a working, debuggable launch script for webstorm.

**Additional context**
[https://github.com/cawa-93/vite-electron-builder/discussions/541](https://github.com/cawa-93/vite-electron-builder/discussions/541)

**Comment by BananaAcid** [comment]
Just as a kickstart, seems to be done resolved here allready: https://github.com/electron-vite/electron-vite-vue/tree/main/.vscode (they teaser it on the github main page)
