### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by busyhe** [cawa-93/vite-electron-builder#863]
**Describe the bug**
when npm install will show error:

❯ npm install
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/busyhe/.npm/_logs/2022-11-01T05_03_28_215Z-debug-0.log

**To Reproduce**

**Expected behavior**
Can Success

**Screenshots**

**Additional context**
remove node_module and package-lock.json can success

**Comment by cawa-93** [comment]
As npm saying you
> This is a problem related to network connectivity.
