### ISSUE TITLE
Cannot open the .exe file after compiling on mac.

### ISSUE THREAD

**Issue by dohooo** [cawa-93/vite-electron-builder#873]
**Describe the bug**
Cannot open the .exe file after compiling on mac.

**To Reproduce**
1. git clone <THIS REPO>
2. npm install
3. npm run compile -w // build for windows platform.
4. Open the `vite-electron-builder.exe`, then nothing happened. No error, No alert, No process..

**Expected behavior**
The application running normally.

**Screenshots**
Nothing happened. No error, No alert, No process.

**Additional context**
building platform: mac
running platform: windows11  in parallels.

**Comment by cawa-93** [comment]
How do you usually run windows apps on mac?

**Comment by cawa-93** [comment]
Try to run app from terminal.

**Comment by dohooo** [comment]
I uses Parallels to do that. Run the app by terminal that you mean in the windows?

**Comment by cawa-93** [comment]
Commonly if app crash for some reason in early stages you will not see any errors in GUI. But may will in CLI
![зображення](https://user-images.githubusercontent.com/1662812/203054011-e42efcb3-287b-4222-9ec3-b0423a691cb5.png)

**Comment by dohooo** [comment]
Oh! Thx for you remind and I'll check it again ASAP.

**Comment by dohooo** [comment]
Can you give me some guidance?
<img width="873" alt="image" src="https://user-images.githubusercontent.com/32405058/203056451-50350bec-bdc4-4165-92dc-1d3e72882e89.png">

I have remove the check-update logic when I re-run the program.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/32405058/203056481-f2ec7528-17cf-4c23-ba85-4bdb1b95805d.png">

**Comment by cawa-93** [comment]
It's some low-level errors 🤷🏻‍♂️ Can't do anithing with that

**Comment by dohooo** [comment]
> It's some low-level errors 🤷🏻‍♂️ Can't do anithing with that

Thanks for you help, I have solved by [this](https://github.com/electron/electron/issues/32074#issuecomment-1155613467).
