### ISSUE TITLE
feat: ESM node integration in separate renderer process

### ISSUE THREAD

**Issue by ThaUnknown** [cawa-93/vite-electron-builder#899]
**Is your feature request related to a problem? Please describe.**
To run node integration inside electron, electron suggests not enabling node integration in any context that loads remote content. This means loading a worker or a new window with node integration enabled, workers however dont have webrtc, so this means it has to be a separate window. ESM support also becomes an issue.

**Describe the solution you'd like**
A 2nd renderer window, with node integration enabled.

**Describe alternatives you've considered**
uuuuuuuuuuh

**Comment by cawa-93** [comment]
You should use node integration how it [described](https://github.com/cawa-93/vite-electron-builder#expose-in-main-world) in docs through preload script.

**Comment by ThaUnknown** [comment]
> You should use node integration how it [described](https://github.com/cawa-93/vite-electron-builder#expose-in-main-world) in docs through preload script.

running node integration inside preload means you can't benefit from threading, and any resource intensive tasks will make the entire UI lag, it additionally can't run a lot of the node API's

**Comment by strogonoff** [comment]
@ThaUnknown what prevents you from spawning another window using Electron’s API? Just as long as you’re sure you aren’t inadvertently giving any way to load something remote in it.
