### ISSUE TITLE
build fails while using tailwindcss

### ISSUE THREAD

**Issue by himalay34** [cawa-93/vite-electron-builder#900]
**Build fails while using tailwindcss**
In development i.e npm run watch , works fine as aspected.
but i  try npm run build, it throws error.
 
![image](https://user-images.githubusercontent.com/54813967/216402313-363fd848-72fb-4449-b84d-f05b551c8bbd.png)

project structure:

![image](https://user-images.githubusercontent.com/54813967/216402842-e47720fe-2a86-42f0-9c7d-bfb35a9aff1a.png)

#### postcss.config.js
![image](https://user-images.githubusercontent.com/54813967/216403012-217ce169-2ef9-4231-b97a-65a70a386d18.png)

#### tailwind.config.js
![image](https://user-images.githubusercontent.com/54813967/216403207-0f558982-f1a9-4d4c-9b5e-e97a5fea4159.png)

**Comment by vietanhlehuu** [comment]
Try this, in `postcss.config.js` file: 

```js
const path = require('path');

module.exports = {
  plugins: {
    tailwindcss: {
      config: path.join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
  },
};

```

**Comment by himalay34** [comment]
> Try this, in `postcss.config.js` file:
> 
> ```js
> const path = require('path');
> 
> module.exports = {
>   plugins: {
>     tailwindcss: {
>       config: path.join(__dirname, 'tailwind.config.js'),
>     },
>     autoprefixer: {},
>   },
> };
> ```

thanks.... ❤️
