### ISSUE TITLE
Vue Devtools

### ISSUE THREAD

**Issue by Imaginativeone** [cawa-93/vite-electron-builder#909]
**Is your feature request related to a problem? Please describe.**

In the Vue version(s), how do I add Vue Devtools?

**Describe the solution you'd like**

I would love to work on Vue Components with TDD. For that, a valuable tool is Vue Devtools. Can you include that?

**Describe alternatives you've considered**

**Additional context**

**Comment by cawa-93** [comment]
https://github.com/cawa-93/vite-electron-builder/blob/0ae2c726641a323145a6c247f374900a7e8b4cf4/packages/main/src/index.ts#L43-L56
