### ISSUE TITLE
electron-builder to electron-forge

### ISSUE THREAD

**Issue by MansourWolou** [cawa-93/vite-electron-builder#916]
vite-lecectron-builder is based on the last version of electron-builder but since eflectron support only electron-forge will you switch to electron-forge? 

Thks

**Comment by cawa-93** [comment]
For few minor reasons:
1. Base idea for this template was to use electron-builder
2. When it started electron-forge wasn't supported well
3. I just like electron-builder 🤷🏻‍♂️
