### ISSUE TITLE
App failed to load renderer page when path contains hash sign (`#`) in Windows prod

### ISSUE THREAD

**Issue by Tanimodori** [cawa-93/vite-electron-builder#925]
**Describe the bug**
The production build of this app won't load the renderer page when its path contains hash sign in Windows.

**To Reproduce**

```bash
git clone https://github.com/cawa-93/vite-electron-builder.git
cd vite-electron-builder
npm i
npm run compile
cd dist
mv win-unpacked #
cd #
./vite-electron-builder.exe
```

**Expected behavior**
The app will run normally

**Screenshots**

![ConEmu64_ZV29mSMHGQ](https://user-images.githubusercontent.com/29478770/232719101-05177ee4-c3df-48e1-aec2-707d187aabc5.png)

![vite-electron-builder_sQcQZcIkfi](https://user-images.githubusercontent.com/29478770/232719132-233b031c-2c6c-4dd8-ad46-058177aecd24.png)

![vite-electron-builder_K4BCsBAdAY](https://user-images.githubusercontent.com/29478770/232719224-57312940-64c8-4ccf-a6e5-a2f7f4054102.png)

**Additional context**
This is a known issue that WHATWG URL API doesn't expect `#` shown in the path of URL and interpret it as anchor of the web page. [Nodejs legacy URL](https://nodejs.org/dist/latest-v18.x/docs/api/url.html#legacy-url-api) provides better support for native URLs. The WHATWG URL API that Nodejs adopted is not fully compatible with the legacy URL APIs.

There are solutions using [`url.parse`](https://nodejs.org/dist/latest-v18.x/docs/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost). But unfortunately it is marked as "deprecated" rather than "legacy" for unknown reason despite [the nodejs team said "We've backed off the deprecation of the legacy API"](https://github.com/nodejs/node/issues/12682#issuecomment-834642460). I propose that we can use [`BrowserWindow.loadFile`](https://www.electronjs.org/docs/latest/api/browser-window#winloadurlurl-options) provided by electron since it is not marked as deprecated or legacy yet. Although I suppose it uses those Nodejs legacy URL API internally lol.

See also 
- https://github.com/nodejs/node/issues/12682
- https://github.com/electron/electron/issues/6869

**Comment by cawa-93** [comment]
`npm run compile` is not actually production build, because in real production build all app files are packed into asar archive. That case should be tested as well. To do that, you can change `compile` command like so:
```
cross-env MODE=production npm run build && electron-builder build --config .electron-builder.config.js
```

**Comment by Tanimodori** [comment]
> `npm run compile` is not actually production build, because in real production build all app's files are packed into asar archive. That case should be tested as well. To do that, you can change `compile` command like so:
> 
> ```
> cross-env MODE=production npm run build && electron-builder build --config .electron-builder.config.js
> ```

I've tested the pr with this build command which works in my local env.

**Comment by cawa-93** [comment]
I mean, does issue with `#` reproduces in "real production" build?

**Comment by Tanimodori** [comment]
It is reproducable with the actual prod build command on the original repo. Just modify the path to include a "#".

**Comment by Tanimodori** [comment]
Thanks!
