### ISSUE TITLE
Auto update from electron-builder isn't working

### ISSUE THREAD

**Issue by Martiinii** [cawa-93/vite-electron-builder#935]
**Describe the bug**
Auto update from electron-builder is not working properly, throwing different errors on different os.

**To Reproduce**

1. Clone repo using 'Use this template'
2. Change github action settings from read to read and write permission
3. Commit and push changes
4. Change from draft release to public and download, install, run (app is working)
5. When we run app through terminal we can see electron updater is throwing errors (app is working)
6. We can change version, text, commit and release and app won't be updated

**Expected behavior**
electron-updater shouldn't throw errors

**Additional context**
Tested on Windows 10 and Linux Mint multiple times, using different settings

Error on linux: (Doesn't throw on unpacked version via npm run compile)
```
Failed check and install updates: Error: ENOTDIR: not a directory, stat '/opt/elap/resources/app.asar/packages/main/dist/node_modules/electron-updater'
    at statSync (node:fs:1596:3)
    at tryStatSync (node:internal/modules/esm/resolve:176:13)
    at packageResolve (node:internal/modules/esm/resolve:864:18)
    at moduleResolve (node:internal/modules/esm/resolve:944:20)
    at defaultResolve (node:internal/modules/esm/resolve:1159:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1166:29) {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/opt/elap/resources/app.asar/packages/main/dist/node_modules/electron-updater'
}
``` 

Errors on Windows:
On unpacked version (npm run compile):
```
Checking for update
Error: Error: ENOENT: no such file or directory, open 'C:\Users\Martini\MProjects\elap\dist\win-unpacked\resources\app-update.yml'
Failed check and install updates: [Error: ENOENT: no such file or directory, open 'C:\Users\Martini\MProjects\elap\dist\win-unpacked\resources\app-update.yml'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Martini\\MProjects\\elap\\dist\\win-unpacked\\resources\\app-update.yml'
}
```

On release:
```
Failed check and install updates: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'electron-updater' imported from C:\Users\Martini\AppData\Local\Programs\elap\resources\app.asar\packages\main\dist\index.cjs
Did you mean to import electron-updater/out/main.js?
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:895:9)
    at moduleResolve (node:internal/modules/esm/resolve:944:20)
    at defaultResolve (node:internal/modules/esm/resolve:1159:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1166:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Another thing I've found out: Using `npx --no-install electron-builder --config .electron-builder.config.js` and then running unpacked version on Windows it doesn't throw any error. It actually works, it downloads latest version and tries to install it on exit, but since it was run using unpacked version there is some conflict I guess.

**Comment by wangjing013** [comment]
+1

**Comment by wangjing013** [comment]
Temporarily fix the problem，electron-updater does not use dynamic imports

Open the packages/main/src/index.ts file

```js
// ...
if (import.meta.env.PROD) {
  app
    .whenReady()
    .then(() => {
      globalShortcut.register('CommandOrControl+Shift+I', () => {
        BrowserWindow.getFocusedWindow()?.webContents.openDevTools();
      });
    })
    .then(() => import('electron-updater'))
    .then(module => {
      const autoUpdater =
        module.autoUpdater || (module.default.autoUpdater as (typeof module)['autoUpdater']);
      return autoUpdater.checkForUpdatesAndNotify();
    })
    .catch(e => console.error('Failed check and install updates:', e));
  app.on('will-quit', () => {
    globalShortcut.unregisterAll();
  });
}
```

Replace the above code with  

```js

import electronUpdater from 'electron-updater';
//...
if (import.meta.env.PROD) {
  app
    .whenReady()
    .then(() => {
      globalShortcut.register('CommandOrControl+Shift+I', () => {
        BrowserWindow.getFocusedWindow()?.webContents.openDevTools();
      });
    })
    .then(() => {
      const autoUpdater = electronUpdater.autoUpdater;
      return autoUpdater.checkForUpdatesAndNotify();
    })
    .catch(e => console.error('Failed check and install updates:', e));
  app.on('will-quit', () => {
    globalShortcut.unregisterAll();
  });
}
```

**Comment by Martiinii** [comment]
> Temporarily fix the problem，electron-updater does not use dynamic imports
> 
> Open the packages/main/src/index.ts file
> 
> ```js
> // ...
> if (import.meta.env.PROD) {
>   app
>     .whenReady()
>     .then(() => {
>       globalShortcut.register('CommandOrControl+Shift+I', () => {
>         BrowserWindow.getFocusedWindow()?.webContents.openDevTools();
>       });
>     })
>     .then(() => import('electron-updater'))
>     .then(module => {
>       const autoUpdater =
>         module.autoUpdater || (module.default.autoUpdater as (typeof module)['autoUpdater']);
>       return autoUpdater.checkForUpdatesAndNotify();
>     })
>     .catch(e => console.error('Failed check and install updates:', e));
>   app.on('will-quit', () => {
>     globalShortcut.unregisterAll();
>   });
> }
> ```
> 
> Replace the above code with  
> 
> ```js
> 
> import electronUpdater from 'electron-updater';
> //...
> if (import.meta.env.PROD) {
>   app
>     .whenReady()
>     .then(() => {
>       globalShortcut.register('CommandOrControl+Shift+I', () => {
>         BrowserWindow.getFocusedWindow()?.webContents.openDevTools();
>       });
>     })
>     .then(() => {
>       const autoUpdater = electronUpdater.autoUpdater;
>       return autoUpdater.checkForUpdatesAndNotify();
>     })
>     .catch(e => console.error('Failed check and install updates:', e));
>   app.on('will-quit', () => {
>     globalShortcut.unregisterAll();
>   });
> }
> ```

Thanks for replying I've already fixed that but forgot to post update here. Your solution is correct and working

**Comment by cawa-93** [comment]
I apologize for the long response with this. You know... my country in war now, so, 🤷‍♂️
