### ISSUE TITLE
Latest Version is broken on pnpm Watch

### ISSUE THREAD

**Issue by FernieRealEstate** [cawa-93/vite-electron-builder#975]
**Describe the bug**
Calling pnpm watch, it cannot find some files:

Library not loaded: @rpath/Squirrel.framework/Squirrel
Library not loaded: @rpath/ReactiveObjC.framework/ReactiveObjC
Library not loaded: @rpath/Mantle.framework/Mantle

I manually edited the node_modules folder to get the paths to match the error message. It works now, but will break again

Wanted path: node_modules/electron/dist/Electron.app/Contents/Frameworks/Squirrel.framework/Squirrel

Actual path:
node_modules/electron/dist/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel

The difference is "/Version/A/"

Weird?

**Comment by cawa-93** [comment]
When it breaks? I not testing and have not opportunity to support all package managers 😔 Maybe someone else can help 🤞

**Comment by FernieRealEstate** [comment]
The odd thing is that I cloned your repo a few days ago and it worked fine. So maybe something changed with the latest commit.
